namespace LMS.View
{
    partial class FrmAddBooks
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmAddBooks));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuFormControlBox1 = new Bunifu.UI.WinForms.BunifuFormControlBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.TxtBookTitle = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.TxtAuthor = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtPublisher = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.cmbCategory = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtQuantity = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pbCover = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.BtnCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnAddBook = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnUpdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuFormDrag1 = new Bunifu.UI.WinForms.BunifuFormDrag();
            this.dtpPubyear = new System.Windows.Forms.DateTimePicker();
            this.DropDownBookType = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.TxtBookSummary = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            ((System.ComponentModel.ISupportInitialize)(this.pbCover)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuFormControlBox1
            // 
            this.bunifuFormControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuFormControlBox1.BunifuFormDrag = null;
            this.bunifuFormControlBox1.CloseBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.CloseBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.CloseBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.CloseBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.CloseBoxOptions.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.CloseBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.CloseBoxOptions.Icon")));
            this.bunifuFormControlBox1.CloseBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.CloseBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.CloseBoxOptions.IconHoverColor = System.Drawing.Color.White;
            this.bunifuFormControlBox1.CloseBoxOptions.IconPressedColor = System.Drawing.Color.White;
            this.bunifuFormControlBox1.CloseBoxOptions.IconSize = new System.Drawing.Size(18, 18);
            this.bunifuFormControlBox1.CloseBoxOptions.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.HelpBox = false;
            this.bunifuFormControlBox1.HelpBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.HelpBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.HelpBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.HelpBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.HelpBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.HelpBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.HelpBoxOptions.Icon")));
            this.bunifuFormControlBox1.HelpBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.HelpBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconSize = new System.Drawing.Size(22, 22);
            this.bunifuFormControlBox1.HelpBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Location = new System.Drawing.Point(479, -2);
            this.bunifuFormControlBox1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuFormControlBox1.MaximizeBox = false;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconAlt = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.IconAlt")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconSize = new System.Drawing.Size(16, 16);
            this.bunifuFormControlBox1.MaximizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.MinimizeBox = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MinimizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconSize = new System.Drawing.Size(14, 14);
            this.bunifuFormControlBox1.MinimizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Name = "bunifuFormControlBox1";
            this.bunifuFormControlBox1.ShowDesignBorders = false;
            this.bunifuFormControlBox1.Size = new System.Drawing.Size(137, 27);
            this.bunifuFormControlBox1.TabIndex = 0;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(43, 24);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(174, 25);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Book\'s Information";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.Location = new System.Drawing.Point(24, 80);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(55, 15);
            this.bunifuLabel2.TabIndex = 2;
            this.bunifuLabel2.Text = "Book Title:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TxtBookTitle
            // 
            this.TxtBookTitle.AcceptsReturn = false;
            this.TxtBookTitle.AcceptsTab = false;
            this.TxtBookTitle.AnimationSpeed = 200;
            this.TxtBookTitle.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtBookTitle.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtBookTitle.AutoSizeHeight = true;
            this.TxtBookTitle.BackColor = System.Drawing.Color.White;
            this.TxtBookTitle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtBookTitle.BackgroundImage")));
            this.TxtBookTitle.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtBookTitle.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtBookTitle.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtBookTitle.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtBookTitle.BorderRadius = 1;
            this.TxtBookTitle.BorderThickness = 1;
            this.TxtBookTitle.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.TxtBookTitle.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtBookTitle.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtBookTitle.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtBookTitle.DefaultText = "";
            this.TxtBookTitle.FillColor = System.Drawing.Color.White;
            this.TxtBookTitle.HideSelection = true;
            this.TxtBookTitle.IconLeft = null;
            this.TxtBookTitle.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtBookTitle.IconPadding = 10;
            this.TxtBookTitle.IconRight = null;
            this.TxtBookTitle.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtBookTitle.Lines = new string[0];
            this.TxtBookTitle.Location = new System.Drawing.Point(24, 101);
            this.TxtBookTitle.MaxLength = 32767;
            this.TxtBookTitle.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtBookTitle.Modified = false;
            this.TxtBookTitle.Multiline = false;
            this.TxtBookTitle.Name = "TxtBookTitle";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtBookTitle.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtBookTitle.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtBookTitle.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtBookTitle.OnIdleState = stateProperties24;
            this.TxtBookTitle.Padding = new System.Windows.Forms.Padding(3);
            this.TxtBookTitle.PasswordChar = '\0';
            this.TxtBookTitle.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtBookTitle.PlaceholderText = "Enter Book Title";
            this.TxtBookTitle.ReadOnly = false;
            this.TxtBookTitle.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtBookTitle.SelectedText = "";
            this.TxtBookTitle.SelectionLength = 0;
            this.TxtBookTitle.SelectionStart = 0;
            this.TxtBookTitle.ShortcutsEnabled = true;
            this.TxtBookTitle.Size = new System.Drawing.Size(220, 39);
            this.TxtBookTitle.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtBookTitle.TabIndex = 3;
            this.TxtBookTitle.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtBookTitle.TextMarginBottom = 0;
            this.TxtBookTitle.TextMarginLeft = 3;
            this.TxtBookTitle.TextMarginTop = 1;
            this.TxtBookTitle.TextPlaceholder = "Enter Book Title";
            this.TxtBookTitle.UseSystemPasswordChar = false;
            this.TxtBookTitle.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(24, 143);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(40, 15);
            this.bunifuLabel3.TabIndex = 4;
            this.bunifuLabel3.Text = "Author:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TxtAuthor
            // 
            this.TxtAuthor.AcceptsReturn = false;
            this.TxtAuthor.AcceptsTab = false;
            this.TxtAuthor.AnimationSpeed = 200;
            this.TxtAuthor.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtAuthor.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtAuthor.AutoSizeHeight = true;
            this.TxtAuthor.BackColor = System.Drawing.Color.White;
            this.TxtAuthor.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtAuthor.BackgroundImage")));
            this.TxtAuthor.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtAuthor.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtAuthor.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtAuthor.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtAuthor.BorderRadius = 1;
            this.TxtAuthor.BorderThickness = 1;
            this.TxtAuthor.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.TxtAuthor.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtAuthor.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtAuthor.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtAuthor.DefaultText = "";
            this.TxtAuthor.FillColor = System.Drawing.Color.White;
            this.TxtAuthor.HideSelection = true;
            this.TxtAuthor.IconLeft = null;
            this.TxtAuthor.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtAuthor.IconPadding = 10;
            this.TxtAuthor.IconRight = null;
            this.TxtAuthor.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtAuthor.Lines = new string[0];
            this.TxtAuthor.Location = new System.Drawing.Point(24, 164);
            this.TxtAuthor.MaxLength = 32767;
            this.TxtAuthor.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtAuthor.Modified = false;
            this.TxtAuthor.Multiline = false;
            this.TxtAuthor.Name = "TxtAuthor";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtAuthor.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtAuthor.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtAuthor.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtAuthor.OnIdleState = stateProperties28;
            this.TxtAuthor.Padding = new System.Windows.Forms.Padding(3);
            this.TxtAuthor.PasswordChar = '\0';
            this.TxtAuthor.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtAuthor.PlaceholderText = "Enter Author";
            this.TxtAuthor.ReadOnly = false;
            this.TxtAuthor.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtAuthor.SelectedText = "";
            this.TxtAuthor.SelectionLength = 0;
            this.TxtAuthor.SelectionStart = 0;
            this.TxtAuthor.ShortcutsEnabled = true;
            this.TxtAuthor.Size = new System.Drawing.Size(220, 39);
            this.TxtAuthor.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtAuthor.TabIndex = 5;
            this.TxtAuthor.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtAuthor.TextMarginBottom = 0;
            this.TxtAuthor.TextMarginLeft = 3;
            this.TxtAuthor.TextMarginTop = 1;
            this.TxtAuthor.TextPlaceholder = "Enter Author";
            this.TxtAuthor.UseSystemPasswordChar = false;
            this.TxtAuthor.WordWrap = true;
            // 
            // TxtPublisher
            // 
            this.TxtPublisher.AcceptsReturn = false;
            this.TxtPublisher.AcceptsTab = false;
            this.TxtPublisher.AnimationSpeed = 200;
            this.TxtPublisher.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtPublisher.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtPublisher.AutoSizeHeight = true;
            this.TxtPublisher.BackColor = System.Drawing.Color.White;
            this.TxtPublisher.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtPublisher.BackgroundImage")));
            this.TxtPublisher.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtPublisher.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtPublisher.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtPublisher.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtPublisher.BorderRadius = 1;
            this.TxtPublisher.BorderThickness = 1;
            this.TxtPublisher.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.TxtPublisher.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtPublisher.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPublisher.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtPublisher.DefaultText = "";
            this.TxtPublisher.FillColor = System.Drawing.Color.White;
            this.TxtPublisher.HideSelection = true;
            this.TxtPublisher.IconLeft = null;
            this.TxtPublisher.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPublisher.IconPadding = 10;
            this.TxtPublisher.IconRight = null;
            this.TxtPublisher.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPublisher.Lines = new string[0];
            this.TxtPublisher.Location = new System.Drawing.Point(24, 226);
            this.TxtPublisher.MaxLength = 32767;
            this.TxtPublisher.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtPublisher.Modified = false;
            this.TxtPublisher.Multiline = false;
            this.TxtPublisher.Name = "TxtPublisher";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtPublisher.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtPublisher.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtPublisher.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtPublisher.OnIdleState = stateProperties32;
            this.TxtPublisher.Padding = new System.Windows.Forms.Padding(3);
            this.TxtPublisher.PasswordChar = '\0';
            this.TxtPublisher.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtPublisher.PlaceholderText = "Enter Publisher";
            this.TxtPublisher.ReadOnly = false;
            this.TxtPublisher.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtPublisher.SelectedText = "";
            this.TxtPublisher.SelectionLength = 0;
            this.TxtPublisher.SelectionStart = 0;
            this.TxtPublisher.ShortcutsEnabled = true;
            this.TxtPublisher.Size = new System.Drawing.Size(220, 39);
            this.TxtPublisher.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtPublisher.TabIndex = 7;
            this.TxtPublisher.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtPublisher.TextMarginBottom = 0;
            this.TxtPublisher.TextMarginLeft = 3;
            this.TxtPublisher.TextMarginTop = 1;
            this.TxtPublisher.TextPlaceholder = "Enter Publisher";
            this.TxtPublisher.UseSystemPasswordChar = false;
            this.TxtPublisher.WordWrap = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel4.Location = new System.Drawing.Point(24, 205);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(52, 15);
            this.bunifuLabel4.TabIndex = 6;
            this.bunifuLabel4.Text = "Publisher:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel5.Location = new System.Drawing.Point(24, 270);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(81, 15);
            this.bunifuLabel5.TabIndex = 9;
            this.bunifuLabel5.Text = "Year Published:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel6.Location = new System.Drawing.Point(24, 319);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(51, 15);
            this.bunifuLabel6.TabIndex = 10;
            this.bunifuLabel6.Text = "Category:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // cmbCategory
            // 
            this.cmbCategory.BackColor = System.Drawing.Color.Transparent;
            this.cmbCategory.BackgroundColor = System.Drawing.Color.White;
            this.cmbCategory.BorderColor = System.Drawing.Color.Silver;
            this.cmbCategory.BorderRadius = 1;
            this.cmbCategory.Color = System.Drawing.Color.Silver;
            this.cmbCategory.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbCategory.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbCategory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbCategory.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbCategory.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbCategory.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbCategory.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbCategory.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbCategory.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCategory.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbCategory.FillDropDown = true;
            this.cmbCategory.FillIndicator = false;
            this.cmbCategory.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbCategory.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cmbCategory.ForeColor = System.Drawing.Color.Black;
            this.cmbCategory.FormattingEnabled = true;
            this.cmbCategory.Icon = null;
            this.cmbCategory.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbCategory.IndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbCategory.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbCategory.IndicatorThickness = 2;
            this.cmbCategory.IsDropdownOpened = false;
            this.cmbCategory.ItemBackColor = System.Drawing.Color.White;
            this.cmbCategory.ItemBorderColor = System.Drawing.Color.White;
            this.cmbCategory.ItemForeColor = System.Drawing.Color.Black;
            this.cmbCategory.ItemHeight = 26;
            this.cmbCategory.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cmbCategory.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbCategory.Items.AddRange(new object[] {
            "Reserved"});
            this.cmbCategory.ItemTopMargin = 3;
            this.cmbCategory.Location = new System.Drawing.Point(24, 340);
            this.cmbCategory.Name = "cmbCategory";
            this.cmbCategory.Size = new System.Drawing.Size(217, 32);
            this.cmbCategory.TabIndex = 11;
            this.cmbCategory.Text = null;
            this.cmbCategory.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbCategory.TextLeftMargin = 5;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel7.Location = new System.Drawing.Point(24, 379);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(49, 15);
            this.bunifuLabel7.TabIndex = 12;
            this.bunifuLabel7.Text = "Quantity:";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtQuantity
            // 
            this.txtQuantity.AcceptsReturn = false;
            this.txtQuantity.AcceptsTab = false;
            this.txtQuantity.AnimationSpeed = 200;
            this.txtQuantity.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtQuantity.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtQuantity.AutoSizeHeight = true;
            this.txtQuantity.BackColor = System.Drawing.Color.White;
            this.txtQuantity.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtQuantity.BackgroundImage")));
            this.txtQuantity.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtQuantity.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtQuantity.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtQuantity.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtQuantity.BorderRadius = 1;
            this.txtQuantity.BorderThickness = 1;
            this.txtQuantity.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtQuantity.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtQuantity.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQuantity.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtQuantity.DefaultText = "";
            this.txtQuantity.FillColor = System.Drawing.Color.White;
            this.txtQuantity.HideSelection = true;
            this.txtQuantity.IconLeft = null;
            this.txtQuantity.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQuantity.IconPadding = 10;
            this.txtQuantity.IconRight = null;
            this.txtQuantity.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQuantity.Lines = new string[0];
            this.txtQuantity.Location = new System.Drawing.Point(24, 396);
            this.txtQuantity.MaxLength = 32767;
            this.txtQuantity.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtQuantity.Modified = false;
            this.txtQuantity.Multiline = false;
            this.txtQuantity.Name = "txtQuantity";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQuantity.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtQuantity.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQuantity.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQuantity.OnIdleState = stateProperties36;
            this.txtQuantity.Padding = new System.Windows.Forms.Padding(3);
            this.txtQuantity.PasswordChar = '\0';
            this.txtQuantity.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtQuantity.PlaceholderText = "Enter Quantity";
            this.txtQuantity.ReadOnly = false;
            this.txtQuantity.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtQuantity.SelectedText = "";
            this.txtQuantity.SelectionLength = 0;
            this.txtQuantity.SelectionStart = 0;
            this.txtQuantity.ShortcutsEnabled = true;
            this.txtQuantity.Size = new System.Drawing.Size(220, 39);
            this.txtQuantity.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtQuantity.TabIndex = 13;
            this.txtQuantity.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtQuantity.TextMarginBottom = 0;
            this.txtQuantity.TextMarginLeft = 3;
            this.txtQuantity.TextMarginTop = 1;
            this.txtQuantity.TextPlaceholder = "Enter Quantity";
            this.txtQuantity.UseSystemPasswordChar = false;
            this.txtQuantity.WordWrap = true;
            // 
            // pbCover
            // 
            this.pbCover.AllowFocused = false;
            this.pbCover.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pbCover.AutoSizeHeight = false;
            this.pbCover.BorderRadius = 0;
            this.pbCover.Image = ((System.Drawing.Image)(resources.GetObject("pbCover.Image")));
            this.pbCover.IsCircle = true;
            this.pbCover.Location = new System.Drawing.Point(348, 113);
            this.pbCover.Name = "pbCover";
            this.pbCover.Size = new System.Drawing.Size(206, 206);
            this.pbCover.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbCover.TabIndex = 14;
            this.pbCover.TabStop = false;
            this.pbCover.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            this.pbCover.Click += new System.EventHandler(this.pbCover_Click);
            // 
            // BtnCancel
            // 
            this.BtnCancel.AllowAnimations = true;
            this.BtnCancel.AllowMouseEffects = true;
            this.BtnCancel.AllowToggling = false;
            this.BtnCancel.AnimationSpeed = 200;
            this.BtnCancel.AutoGenerateColors = false;
            this.BtnCancel.AutoRoundBorders = true;
            this.BtnCancel.AutoSizeLeftIcon = true;
            this.BtnCancel.AutoSizeRightIcon = true;
            this.BtnCancel.BackColor = System.Drawing.Color.Transparent;
            this.BtnCancel.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCancel.BackgroundImage")));
            this.BtnCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancel.ButtonText = "Cancel";
            this.BtnCancel.ButtonTextMarginLeft = 0;
            this.BtnCancel.ColorContrastOnClick = 45;
            this.BtnCancel.ColorContrastOnHover = 45;
            this.BtnCancel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.BtnCancel.CustomizableEdges = borderEdges4;
            this.BtnCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCancel.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnCancel.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCancel.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnCancel.ForeColor = System.Drawing.Color.White;
            this.BtnCancel.IconLeft = null;
            this.BtnCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCancel.IconMarginLeft = 11;
            this.BtnCancel.IconPadding = 10;
            this.BtnCancel.IconRight = null;
            this.BtnCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCancel.IconSize = 25;
            this.BtnCancel.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnCancel.IdleBorderRadius = 0;
            this.BtnCancel.IdleBorderThickness = 0;
            this.BtnCancel.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnCancel.IdleIconLeftImage = null;
            this.BtnCancel.IdleIconRightImage = null;
            this.BtnCancel.IndicateFocus = false;
            this.BtnCancel.Location = new System.Drawing.Point(311, 420);
            this.BtnCancel.Name = "BtnCancel";
            this.BtnCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCancel.OnDisabledState.BorderRadius = 33;
            this.BtnCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancel.OnDisabledState.BorderThickness = 1;
            this.BtnCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCancel.OnDisabledState.IconLeftImage = null;
            this.BtnCancel.OnDisabledState.IconRightImage = null;
            this.BtnCancel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.BtnCancel.onHoverState.BorderRadius = 33;
            this.BtnCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancel.onHoverState.BorderThickness = 1;
            this.BtnCancel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.BtnCancel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCancel.onHoverState.IconLeftImage = null;
            this.BtnCancel.onHoverState.IconRightImage = null;
            this.BtnCancel.OnIdleState.BorderColor = System.Drawing.Color.Red;
            this.BtnCancel.OnIdleState.BorderRadius = 33;
            this.BtnCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancel.OnIdleState.BorderThickness = 1;
            this.BtnCancel.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.BtnCancel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCancel.OnIdleState.IconLeftImage = null;
            this.BtnCancel.OnIdleState.IconRightImage = null;
            this.BtnCancel.OnPressedState.BorderColor = System.Drawing.Color.Maroon;
            this.BtnCancel.OnPressedState.BorderRadius = 33;
            this.BtnCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancel.OnPressedState.BorderThickness = 1;
            this.BtnCancel.OnPressedState.FillColor = System.Drawing.Color.Maroon;
            this.BtnCancel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCancel.OnPressedState.IconLeftImage = null;
            this.BtnCancel.OnPressedState.IconRightImage = null;
            this.BtnCancel.Size = new System.Drawing.Size(86, 33);
            this.BtnCancel.TabIndex = 15;
            this.BtnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCancel.TextMarginLeft = 0;
            this.BtnCancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCancel.UseDefaultRadiusAndThickness = true;
            // 
            // BtnAddBook
            // 
            this.BtnAddBook.AllowAnimations = true;
            this.BtnAddBook.AllowMouseEffects = true;
            this.BtnAddBook.AllowToggling = false;
            this.BtnAddBook.AnimationSpeed = 200;
            this.BtnAddBook.AutoGenerateColors = false;
            this.BtnAddBook.AutoRoundBorders = true;
            this.BtnAddBook.AutoSizeLeftIcon = true;
            this.BtnAddBook.AutoSizeRightIcon = true;
            this.BtnAddBook.BackColor = System.Drawing.Color.Transparent;
            this.BtnAddBook.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnAddBook.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnAddBook.BackgroundImage")));
            this.BtnAddBook.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAddBook.ButtonText = "Save";
            this.BtnAddBook.ButtonTextMarginLeft = 0;
            this.BtnAddBook.ColorContrastOnClick = 45;
            this.BtnAddBook.ColorContrastOnHover = 45;
            this.BtnAddBook.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.BtnAddBook.CustomizableEdges = borderEdges5;
            this.BtnAddBook.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnAddBook.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnAddBook.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnAddBook.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnAddBook.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnAddBook.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnAddBook.ForeColor = System.Drawing.Color.White;
            this.BtnAddBook.IconLeft = null;
            this.BtnAddBook.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnAddBook.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnAddBook.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnAddBook.IconMarginLeft = 11;
            this.BtnAddBook.IconPadding = 10;
            this.BtnAddBook.IconRight = null;
            this.BtnAddBook.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnAddBook.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnAddBook.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnAddBook.IconSize = 25;
            this.BtnAddBook.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnAddBook.IdleBorderRadius = 0;
            this.BtnAddBook.IdleBorderThickness = 0;
            this.BtnAddBook.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnAddBook.IdleIconLeftImage = null;
            this.BtnAddBook.IdleIconRightImage = null;
            this.BtnAddBook.IndicateFocus = false;
            this.BtnAddBook.Location = new System.Drawing.Point(403, 420);
            this.BtnAddBook.Name = "BtnAddBook";
            this.BtnAddBook.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnAddBook.OnDisabledState.BorderRadius = 33;
            this.BtnAddBook.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAddBook.OnDisabledState.BorderThickness = 1;
            this.BtnAddBook.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnAddBook.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnAddBook.OnDisabledState.IconLeftImage = null;
            this.BtnAddBook.OnDisabledState.IconRightImage = null;
            this.BtnAddBook.onHoverState.BorderColor = System.Drawing.Color.Green;
            this.BtnAddBook.onHoverState.BorderRadius = 33;
            this.BtnAddBook.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAddBook.onHoverState.BorderThickness = 1;
            this.BtnAddBook.onHoverState.FillColor = System.Drawing.Color.Green;
            this.BtnAddBook.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnAddBook.onHoverState.IconLeftImage = null;
            this.BtnAddBook.onHoverState.IconRightImage = null;
            this.BtnAddBook.OnIdleState.BorderColor = System.Drawing.Color.Green;
            this.BtnAddBook.OnIdleState.BorderRadius = 33;
            this.BtnAddBook.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAddBook.OnIdleState.BorderThickness = 1;
            this.BtnAddBook.OnIdleState.FillColor = System.Drawing.Color.Green;
            this.BtnAddBook.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnAddBook.OnIdleState.IconLeftImage = null;
            this.BtnAddBook.OnIdleState.IconRightImage = null;
            this.BtnAddBook.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.BtnAddBook.OnPressedState.BorderRadius = 33;
            this.BtnAddBook.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAddBook.OnPressedState.BorderThickness = 1;
            this.BtnAddBook.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.BtnAddBook.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnAddBook.OnPressedState.IconLeftImage = null;
            this.BtnAddBook.OnPressedState.IconRightImage = null;
            this.BtnAddBook.Size = new System.Drawing.Size(86, 33);
            this.BtnAddBook.TabIndex = 16;
            this.BtnAddBook.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnAddBook.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnAddBook.TextMarginLeft = 0;
            this.BtnAddBook.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnAddBook.UseDefaultRadiusAndThickness = true;
            this.BtnAddBook.Click += new System.EventHandler(this.BtnAddBook_Click);
            // 
            // BtnUpdate
            // 
            this.BtnUpdate.AllowAnimations = true;
            this.BtnUpdate.AllowMouseEffects = true;
            this.BtnUpdate.AllowToggling = false;
            this.BtnUpdate.AnimationSpeed = 200;
            this.BtnUpdate.AutoGenerateColors = false;
            this.BtnUpdate.AutoRoundBorders = true;
            this.BtnUpdate.AutoSizeLeftIcon = true;
            this.BtnUpdate.AutoSizeRightIcon = true;
            this.BtnUpdate.BackColor = System.Drawing.Color.Transparent;
            this.BtnUpdate.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnUpdate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnUpdate.BackgroundImage")));
            this.BtnUpdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdate.ButtonText = "Update";
            this.BtnUpdate.ButtonTextMarginLeft = 0;
            this.BtnUpdate.ColorContrastOnClick = 45;
            this.BtnUpdate.ColorContrastOnHover = 45;
            this.BtnUpdate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.BtnUpdate.CustomizableEdges = borderEdges6;
            this.BtnUpdate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnUpdate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnUpdate.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnUpdate.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnUpdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnUpdate.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnUpdate.ForeColor = System.Drawing.Color.White;
            this.BtnUpdate.IconLeft = null;
            this.BtnUpdate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnUpdate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnUpdate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnUpdate.IconMarginLeft = 11;
            this.BtnUpdate.IconPadding = 10;
            this.BtnUpdate.IconRight = null;
            this.BtnUpdate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnUpdate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnUpdate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnUpdate.IconSize = 25;
            this.BtnUpdate.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnUpdate.IdleBorderRadius = 0;
            this.BtnUpdate.IdleBorderThickness = 0;
            this.BtnUpdate.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnUpdate.IdleIconLeftImage = null;
            this.BtnUpdate.IdleIconRightImage = null;
            this.BtnUpdate.IndicateFocus = false;
            this.BtnUpdate.Location = new System.Drawing.Point(495, 420);
            this.BtnUpdate.Name = "BtnUpdate";
            this.BtnUpdate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnUpdate.OnDisabledState.BorderRadius = 33;
            this.BtnUpdate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdate.OnDisabledState.BorderThickness = 1;
            this.BtnUpdate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnUpdate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnUpdate.OnDisabledState.IconLeftImage = null;
            this.BtnUpdate.OnDisabledState.IconRightImage = null;
            this.BtnUpdate.onHoverState.BorderColor = System.Drawing.Color.Blue;
            this.BtnUpdate.onHoverState.BorderRadius = 33;
            this.BtnUpdate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdate.onHoverState.BorderThickness = 1;
            this.BtnUpdate.onHoverState.FillColor = System.Drawing.Color.Blue;
            this.BtnUpdate.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnUpdate.onHoverState.IconLeftImage = null;
            this.BtnUpdate.onHoverState.IconRightImage = null;
            this.BtnUpdate.OnIdleState.BorderColor = System.Drawing.Color.Navy;
            this.BtnUpdate.OnIdleState.BorderRadius = 33;
            this.BtnUpdate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdate.OnIdleState.BorderThickness = 1;
            this.BtnUpdate.OnIdleState.FillColor = System.Drawing.Color.Navy;
            this.BtnUpdate.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnUpdate.OnIdleState.IconLeftImage = null;
            this.BtnUpdate.OnIdleState.IconRightImage = null;
            this.BtnUpdate.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.BtnUpdate.OnPressedState.BorderRadius = 33;
            this.BtnUpdate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdate.OnPressedState.BorderThickness = 1;
            this.BtnUpdate.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.BtnUpdate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnUpdate.OnPressedState.IconLeftImage = null;
            this.BtnUpdate.OnPressedState.IconRightImage = null;
            this.BtnUpdate.Size = new System.Drawing.Size(86, 33);
            this.BtnUpdate.TabIndex = 17;
            this.BtnUpdate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnUpdate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnUpdate.TextMarginLeft = 0;
            this.BtnUpdate.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnUpdate.UseDefaultRadiusAndThickness = true;
            this.BtnUpdate.Click += new System.EventHandler(this.BtnUpdate_Click);
            // 
            // bunifuFormDrag1
            // 
            this.bunifuFormDrag1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDrag1.ContainerControl = this;
            this.bunifuFormDrag1.DockIndicatorsOpacity = 0.5D;
            this.bunifuFormDrag1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDrag1.DockingOptions.DockAll = true;
            this.bunifuFormDrag1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDrag1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDrag1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDrag1.DockingOptions.DockLeft = true;
            this.bunifuFormDrag1.DockingOptions.DockRight = true;
            this.bunifuFormDrag1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDrag1.DockingOptions.DockTopRight = true;
            this.bunifuFormDrag1.DragOpacity = 0.9D;
            this.bunifuFormDrag1.Enabled = true;
            this.bunifuFormDrag1.ParentForm = this;
            this.bunifuFormDrag1.ShowCursorChanges = true;
            this.bunifuFormDrag1.ShowDockingIndicators = true;
            this.bunifuFormDrag1.TitleBarOptions.BunifuFormDrag = this.bunifuFormDrag1;
            this.bunifuFormDrag1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDrag1.TitleBarOptions.Enabled = true;
            this.bunifuFormDrag1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDrag1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // dtpPubyear
            // 
            this.dtpPubyear.CalendarFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpPubyear.CustomFormat = "yyyy";
            this.dtpPubyear.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpPubyear.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtpPubyear.Location = new System.Drawing.Point(24, 291);
            this.dtpPubyear.Name = "dtpPubyear";
            this.dtpPubyear.ShowUpDown = true;
            this.dtpPubyear.Size = new System.Drawing.Size(217, 22);
            this.dtpPubyear.TabIndex = 23;
            // 
            // DropDownBookType
            // 
            this.DropDownBookType.BackColor = System.Drawing.Color.Transparent;
            this.DropDownBookType.BackgroundColor = System.Drawing.Color.White;
            this.DropDownBookType.BorderColor = System.Drawing.Color.Silver;
            this.DropDownBookType.BorderRadius = 1;
            this.DropDownBookType.Color = System.Drawing.Color.Silver;
            this.DropDownBookType.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.DropDownBookType.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.DropDownBookType.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DropDownBookType.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.DropDownBookType.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.DropDownBookType.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.DropDownBookType.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.DropDownBookType.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.DropDownBookType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.DropDownBookType.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.DropDownBookType.FillDropDown = true;
            this.DropDownBookType.FillIndicator = false;
            this.DropDownBookType.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.DropDownBookType.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.DropDownBookType.ForeColor = System.Drawing.Color.Black;
            this.DropDownBookType.FormattingEnabled = true;
            this.DropDownBookType.Icon = null;
            this.DropDownBookType.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.DropDownBookType.IndicatorColor = System.Drawing.Color.DarkGray;
            this.DropDownBookType.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.DropDownBookType.IndicatorThickness = 2;
            this.DropDownBookType.IsDropdownOpened = false;
            this.DropDownBookType.ItemBackColor = System.Drawing.Color.White;
            this.DropDownBookType.ItemBorderColor = System.Drawing.Color.White;
            this.DropDownBookType.ItemForeColor = System.Drawing.Color.Black;
            this.DropDownBookType.ItemHeight = 26;
            this.DropDownBookType.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.DropDownBookType.ItemHighLightForeColor = System.Drawing.Color.White;
            this.DropDownBookType.Items.AddRange(new object[] {
            "Fiction/Nonfiction"});
            this.DropDownBookType.ItemTopMargin = 3;
            this.DropDownBookType.Location = new System.Drawing.Point(24, 464);
            this.DropDownBookType.Name = "DropDownBookType";
            this.DropDownBookType.Size = new System.Drawing.Size(217, 32);
            this.DropDownBookType.TabIndex = 25;
            this.DropDownBookType.Text = null;
            this.DropDownBookType.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.DropDownBookType.TextLeftMargin = 5;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel8.Location = new System.Drawing.Point(24, 443);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(58, 15);
            this.bunifuLabel8.TabIndex = 24;
            this.bunifuLabel8.Text = "Book Type:";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TxtBookSummary
            // 
            this.TxtBookSummary.AcceptsReturn = false;
            this.TxtBookSummary.AcceptsTab = false;
            this.TxtBookSummary.AnimationSpeed = 200;
            this.TxtBookSummary.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtBookSummary.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtBookSummary.AutoSizeHeight = true;
            this.TxtBookSummary.BackColor = System.Drawing.Color.White;
            this.TxtBookSummary.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtBookSummary.BackgroundImage")));
            this.TxtBookSummary.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtBookSummary.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtBookSummary.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtBookSummary.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtBookSummary.BorderRadius = 1;
            this.TxtBookSummary.BorderThickness = 1;
            this.TxtBookSummary.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.TxtBookSummary.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtBookSummary.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtBookSummary.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtBookSummary.DefaultText = "";
            this.TxtBookSummary.FillColor = System.Drawing.Color.White;
            this.TxtBookSummary.HideSelection = true;
            this.TxtBookSummary.IconLeft = null;
            this.TxtBookSummary.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtBookSummary.IconPadding = 10;
            this.TxtBookSummary.IconRight = null;
            this.TxtBookSummary.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtBookSummary.Lines = new string[0];
            this.TxtBookSummary.Location = new System.Drawing.Point(24, 532);
            this.TxtBookSummary.MaxLength = 32767;
            this.TxtBookSummary.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtBookSummary.Modified = false;
            this.TxtBookSummary.Multiline = true;
            this.TxtBookSummary.Name = "TxtBookSummary";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtBookSummary.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtBookSummary.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtBookSummary.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtBookSummary.OnIdleState = stateProperties40;
            this.TxtBookSummary.Padding = new System.Windows.Forms.Padding(3);
            this.TxtBookSummary.PasswordChar = '\0';
            this.TxtBookSummary.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtBookSummary.PlaceholderText = "Enter Summary";
            this.TxtBookSummary.ReadOnly = false;
            this.TxtBookSummary.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtBookSummary.SelectedText = "";
            this.TxtBookSummary.SelectionLength = 0;
            this.TxtBookSummary.SelectionStart = 0;
            this.TxtBookSummary.ShortcutsEnabled = true;
            this.TxtBookSummary.Size = new System.Drawing.Size(220, 29);
            this.TxtBookSummary.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtBookSummary.TabIndex = 27;
            this.TxtBookSummary.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtBookSummary.TextMarginBottom = 0;
            this.TxtBookSummary.TextMarginLeft = 3;
            this.TxtBookSummary.TextMarginTop = 1;
            this.TxtBookSummary.TextPlaceholder = "Enter Summary";
            this.TxtBookSummary.UseSystemPasswordChar = false;
            this.TxtBookSummary.WordWrap = true;
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.CursorType = null;
            this.bunifuLabel9.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel9.Location = new System.Drawing.Point(24, 511);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(51, 15);
            this.bunifuLabel9.TabIndex = 26;
            this.bunifuLabel9.Text = "Summary";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // FrmAddBooks
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(616, 594);
            this.Controls.Add(this.TxtBookSummary);
            this.Controls.Add(this.bunifuLabel9);
            this.Controls.Add(this.DropDownBookType);
            this.Controls.Add(this.bunifuLabel8);
            this.Controls.Add(this.dtpPubyear);
            this.Controls.Add(this.BtnUpdate);
            this.Controls.Add(this.BtnAddBook);
            this.Controls.Add(this.BtnCancel);
            this.Controls.Add(this.pbCover);
            this.Controls.Add(this.txtQuantity);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.cmbCategory);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.TxtPublisher);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.TxtAuthor);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.TxtBookTitle);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.bunifuFormControlBox1);
            this.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FrmAddBooks";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FrmAddBooks";
            ((System.ComponentModel.ISupportInitialize)(this.pbCover)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuFormControlBox bunifuFormControlBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox TxtBookTitle;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox TxtAuthor;
        private Bunifu.UI.WinForms.BunifuTextBox TxtPublisher;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuDropdown cmbCategory;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuTextBox txtQuantity;
        private Bunifu.UI.WinForms.BunifuPictureBox pbCover;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCancel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnAddBook;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnUpdate;
        private Bunifu.UI.WinForms.BunifuFormDrag bunifuFormDrag1;
        private System.Windows.Forms.DateTimePicker dtpPubyear;
        private Bunifu.UI.WinForms.BunifuTextBox TxtBookSummary;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuDropdown DropDownBookType;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
    }
}