namespace LMS.View
{
    partial class FrmAddUser
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmAddUser));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuFormControlBox1 = new Bunifu.UI.WinForms.BunifuFormControlBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.TxtName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.DtpBirthday = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.TxtAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtContactNo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.TxtEmailAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.CmbPosition = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.PbProfile = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.TxtUsername = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            this.TxtConfirmPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel10 = new Bunifu.UI.WinForms.BunifuLabel();
            this.BtnCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.PbProfile)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuFormControlBox1
            // 
            this.bunifuFormControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuFormControlBox1.BunifuFormDrag = null;
            this.bunifuFormControlBox1.CloseBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.CloseBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.CloseBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.CloseBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.CloseBoxOptions.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.CloseBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.CloseBoxOptions.Icon")));
            this.bunifuFormControlBox1.CloseBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.CloseBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.CloseBoxOptions.IconHoverColor = System.Drawing.Color.White;
            this.bunifuFormControlBox1.CloseBoxOptions.IconPressedColor = System.Drawing.Color.White;
            this.bunifuFormControlBox1.CloseBoxOptions.IconSize = new System.Drawing.Size(18, 18);
            this.bunifuFormControlBox1.CloseBoxOptions.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.HelpBox = false;
            this.bunifuFormControlBox1.HelpBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.HelpBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.HelpBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.HelpBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.HelpBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.HelpBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.HelpBoxOptions.Icon")));
            this.bunifuFormControlBox1.HelpBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.HelpBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconSize = new System.Drawing.Size(22, 22);
            this.bunifuFormControlBox1.HelpBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Location = new System.Drawing.Point(508, 0);
            this.bunifuFormControlBox1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuFormControlBox1.MaximizeBox = false;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconAlt = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.IconAlt")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconSize = new System.Drawing.Size(16, 16);
            this.bunifuFormControlBox1.MaximizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.MinimizeBox = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MinimizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconSize = new System.Drawing.Size(14, 14);
            this.bunifuFormControlBox1.MinimizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Name = "bunifuFormControlBox1";
            this.bunifuFormControlBox1.ShowDesignBorders = false;
            this.bunifuFormControlBox1.Size = new System.Drawing.Size(115, 22);
            this.bunifuFormControlBox1.TabIndex = 0;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(182, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(256, 45);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "User Information";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.Location = new System.Drawing.Point(77, 71);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(35, 15);
            this.bunifuLabel2.TabIndex = 2;
            this.bunifuLabel2.Text = "Name:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TxtName
            // 
            this.TxtName.AcceptsReturn = false;
            this.TxtName.AcceptsTab = false;
            this.TxtName.AnimationSpeed = 200;
            this.TxtName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtName.AutoSizeHeight = true;
            this.TxtName.BackColor = System.Drawing.Color.White;
            this.TxtName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtName.BackgroundImage")));
            this.TxtName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtName.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtName.BorderRadius = 1;
            this.TxtName.BorderThickness = 1;
            this.TxtName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.TxtName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtName.DefaultText = "";
            this.TxtName.FillColor = System.Drawing.Color.White;
            this.TxtName.HideSelection = true;
            this.TxtName.IconLeft = null;
            this.TxtName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtName.IconPadding = 10;
            this.TxtName.IconRight = null;
            this.TxtName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtName.Lines = new string[0];
            this.TxtName.Location = new System.Drawing.Point(77, 93);
            this.TxtName.MaxLength = 32767;
            this.TxtName.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtName.Modified = false;
            this.TxtName.Multiline = false;
            this.TxtName.Name = "TxtName";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtName.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtName.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtName.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtName.OnIdleState = stateProperties4;
            this.TxtName.Padding = new System.Windows.Forms.Padding(3);
            this.TxtName.PasswordChar = '\0';
            this.TxtName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtName.PlaceholderText = "Enter Name";
            this.TxtName.ReadOnly = false;
            this.TxtName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtName.SelectedText = "";
            this.TxtName.SelectionLength = 0;
            this.TxtName.SelectionStart = 0;
            this.TxtName.ShortcutsEnabled = true;
            this.TxtName.Size = new System.Drawing.Size(196, 39);
            this.TxtName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtName.TabIndex = 3;
            this.TxtName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtName.TextMarginBottom = 0;
            this.TxtName.TextMarginLeft = 3;
            this.TxtName.TextMarginTop = 1;
            this.TxtName.TextPlaceholder = "Enter Name";
            this.TxtName.UseSystemPasswordChar = false;
            this.TxtName.WordWrap = true;
          
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(77, 148);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(44, 15);
            this.bunifuLabel3.TabIndex = 4;
            this.bunifuLabel3.Text = "Birthday";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // DtpBirthday
            // 
            this.DtpBirthday.BackColor = System.Drawing.Color.Transparent;
            this.DtpBirthday.BorderColor = System.Drawing.Color.Silver;
            this.DtpBirthday.BorderRadius = 1;
            this.DtpBirthday.Color = System.Drawing.Color.Silver;
            this.DtpBirthday.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.DtpBirthday.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.DtpBirthday.DisabledColor = System.Drawing.Color.Gray;
            this.DtpBirthday.DisplayWeekNumbers = false;
            this.DtpBirthday.DPHeight = 0;
            this.DtpBirthday.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.DtpBirthday.FillDatePicker = false;
            this.DtpBirthday.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.DtpBirthday.ForeColor = System.Drawing.Color.Black;
            this.DtpBirthday.Icon = ((System.Drawing.Image)(resources.GetObject("DtpBirthday.Icon")));
            this.DtpBirthday.IconColor = System.Drawing.Color.Green;
            this.DtpBirthday.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.DtpBirthday.LeftTextMargin = 5;
            this.DtpBirthday.Location = new System.Drawing.Point(77, 169);
            this.DtpBirthday.MinimumSize = new System.Drawing.Size(4, 32);
            this.DtpBirthday.Name = "DtpBirthday";
            this.DtpBirthday.Size = new System.Drawing.Size(196, 32);
            this.DtpBirthday.TabIndex = 5;
            this.DtpBirthday.Value = new System.DateTime(2024, 10, 16, 20, 3, 0, 0);
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel4.Location = new System.Drawing.Point(77, 216);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(42, 15);
            this.bunifuLabel4.TabIndex = 6;
            this.bunifuLabel4.Text = "Address";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TxtAddress
            // 
            this.TxtAddress.AcceptsReturn = false;
            this.TxtAddress.AcceptsTab = false;
            this.TxtAddress.AnimationSpeed = 200;
            this.TxtAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtAddress.AutoSizeHeight = true;
            this.TxtAddress.BackColor = System.Drawing.Color.White;
            this.TxtAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtAddress.BackgroundImage")));
            this.TxtAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtAddress.BorderRadius = 1;
            this.TxtAddress.BorderThickness = 1;
            this.TxtAddress.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.TxtAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtAddress.DefaultText = "";
            this.TxtAddress.FillColor = System.Drawing.Color.White;
            this.TxtAddress.HideSelection = true;
            this.TxtAddress.IconLeft = null;
            this.TxtAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtAddress.IconPadding = 10;
            this.TxtAddress.IconRight = null;
            this.TxtAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtAddress.Lines = new string[0];
            this.TxtAddress.Location = new System.Drawing.Point(77, 237);
            this.TxtAddress.MaxLength = 32767;
            this.TxtAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtAddress.Modified = false;
            this.TxtAddress.Multiline = false;
            this.TxtAddress.Name = "TxtAddress";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtAddress.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtAddress.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtAddress.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtAddress.OnIdleState = stateProperties8;
            this.TxtAddress.Padding = new System.Windows.Forms.Padding(3);
            this.TxtAddress.PasswordChar = '\0';
            this.TxtAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtAddress.PlaceholderText = "Enter Address";
            this.TxtAddress.ReadOnly = false;
            this.TxtAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtAddress.SelectedText = "";
            this.TxtAddress.SelectionLength = 0;
            this.TxtAddress.SelectionStart = 0;
            this.TxtAddress.ShortcutsEnabled = true;
            this.TxtAddress.Size = new System.Drawing.Size(196, 39);
            this.TxtAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtAddress.TabIndex = 7;
            this.TxtAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtAddress.TextMarginBottom = 0;
            this.TxtAddress.TextMarginLeft = 3;
            this.TxtAddress.TextMarginTop = 1;
            this.TxtAddress.TextPlaceholder = "Enter Address";
            this.TxtAddress.UseSystemPasswordChar = false;
            this.TxtAddress.WordWrap = true;
            // 
            // TxtContactNo
            // 
            this.TxtContactNo.AcceptsReturn = false;
            this.TxtContactNo.AcceptsTab = false;
            this.TxtContactNo.AnimationSpeed = 200;
            this.TxtContactNo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtContactNo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtContactNo.AutoSizeHeight = true;
            this.TxtContactNo.BackColor = System.Drawing.Color.White;
            this.TxtContactNo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtContactNo.BackgroundImage")));
            this.TxtContactNo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtContactNo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtContactNo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtContactNo.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtContactNo.BorderRadius = 1;
            this.TxtContactNo.BorderThickness = 1;
            this.TxtContactNo.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.TxtContactNo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtContactNo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtContactNo.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtContactNo.DefaultText = "";
            this.TxtContactNo.FillColor = System.Drawing.Color.White;
            this.TxtContactNo.HideSelection = true;
            this.TxtContactNo.IconLeft = null;
            this.TxtContactNo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtContactNo.IconPadding = 10;
            this.TxtContactNo.IconRight = null;
            this.TxtContactNo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtContactNo.Lines = new string[0];
            this.TxtContactNo.Location = new System.Drawing.Point(77, 312);
            this.TxtContactNo.MaxLength = 32767;
            this.TxtContactNo.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtContactNo.Modified = false;
            this.TxtContactNo.Multiline = false;
            this.TxtContactNo.Name = "TxtContactNo";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtContactNo.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtContactNo.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtContactNo.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtContactNo.OnIdleState = stateProperties12;
            this.TxtContactNo.Padding = new System.Windows.Forms.Padding(3);
            this.TxtContactNo.PasswordChar = '\0';
            this.TxtContactNo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtContactNo.PlaceholderText = "Enter Contact No.";
            this.TxtContactNo.ReadOnly = false;
            this.TxtContactNo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtContactNo.SelectedText = "";
            this.TxtContactNo.SelectionLength = 0;
            this.TxtContactNo.SelectionStart = 0;
            this.TxtContactNo.ShortcutsEnabled = true;
            this.TxtContactNo.Size = new System.Drawing.Size(196, 39);
            this.TxtContactNo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtContactNo.TabIndex = 9;
            this.TxtContactNo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtContactNo.TextMarginBottom = 0;
            this.TxtContactNo.TextMarginLeft = 3;
            this.TxtContactNo.TextMarginTop = 1;
            this.TxtContactNo.TextPlaceholder = "Enter Contact No.";
            this.TxtContactNo.UseSystemPasswordChar = false;
            this.TxtContactNo.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel5.Location = new System.Drawing.Point(77, 291);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(64, 15);
            this.bunifuLabel5.TabIndex = 8;
            this.bunifuLabel5.Text = "Contact No.";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TxtEmailAddress
            // 
            this.TxtEmailAddress.AcceptsReturn = false;
            this.TxtEmailAddress.AcceptsTab = false;
            this.TxtEmailAddress.AnimationSpeed = 200;
            this.TxtEmailAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtEmailAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtEmailAddress.AutoSizeHeight = true;
            this.TxtEmailAddress.BackColor = System.Drawing.Color.White;
            this.TxtEmailAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtEmailAddress.BackgroundImage")));
            this.TxtEmailAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtEmailAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtEmailAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtEmailAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtEmailAddress.BorderRadius = 1;
            this.TxtEmailAddress.BorderThickness = 1;
            this.TxtEmailAddress.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.TxtEmailAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtEmailAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtEmailAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtEmailAddress.DefaultText = "";
            this.TxtEmailAddress.FillColor = System.Drawing.Color.White;
            this.TxtEmailAddress.HideSelection = true;
            this.TxtEmailAddress.IconLeft = null;
            this.TxtEmailAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtEmailAddress.IconPadding = 10;
            this.TxtEmailAddress.IconRight = null;
            this.TxtEmailAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtEmailAddress.Lines = new string[0];
            this.TxtEmailAddress.Location = new System.Drawing.Point(77, 389);
            this.TxtEmailAddress.MaxLength = 32767;
            this.TxtEmailAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtEmailAddress.Modified = false;
            this.TxtEmailAddress.Multiline = false;
            this.TxtEmailAddress.Name = "TxtEmailAddress";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtEmailAddress.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtEmailAddress.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtEmailAddress.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtEmailAddress.OnIdleState = stateProperties16;
            this.TxtEmailAddress.Padding = new System.Windows.Forms.Padding(3);
            this.TxtEmailAddress.PasswordChar = '\0';
            this.TxtEmailAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtEmailAddress.PlaceholderText = "Enter Email Address";
            this.TxtEmailAddress.ReadOnly = false;
            this.TxtEmailAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtEmailAddress.SelectedText = "";
            this.TxtEmailAddress.SelectionLength = 0;
            this.TxtEmailAddress.SelectionStart = 0;
            this.TxtEmailAddress.ShortcutsEnabled = true;
            this.TxtEmailAddress.Size = new System.Drawing.Size(196, 39);
            this.TxtEmailAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtEmailAddress.TabIndex = 11;
            this.TxtEmailAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtEmailAddress.TextMarginBottom = 0;
            this.TxtEmailAddress.TextMarginLeft = 3;
            this.TxtEmailAddress.TextMarginTop = 1;
            this.TxtEmailAddress.TextPlaceholder = "Enter Email Address";
            this.TxtEmailAddress.UseSystemPasswordChar = false;
            this.TxtEmailAddress.WordWrap = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel6.Location = new System.Drawing.Point(77, 368);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(74, 15);
            this.bunifuLabel6.TabIndex = 10;
            this.bunifuLabel6.Text = "Email Address";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // CmbPosition
            // 
            this.CmbPosition.BackColor = System.Drawing.Color.Transparent;
            this.CmbPosition.BackgroundColor = System.Drawing.Color.White;
            this.CmbPosition.BorderColor = System.Drawing.Color.Silver;
            this.CmbPosition.BorderRadius = 1;
            this.CmbPosition.Color = System.Drawing.Color.Silver;
            this.CmbPosition.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.CmbPosition.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.CmbPosition.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CmbPosition.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.CmbPosition.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.CmbPosition.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.CmbPosition.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.CmbPosition.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.CmbPosition.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.CmbPosition.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.CmbPosition.FillDropDown = true;
            this.CmbPosition.FillIndicator = false;
            this.CmbPosition.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.CmbPosition.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.CmbPosition.ForeColor = System.Drawing.Color.Black;
            this.CmbPosition.FormattingEnabled = true;
            this.CmbPosition.Icon = null;
            this.CmbPosition.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.CmbPosition.IndicatorColor = System.Drawing.Color.DarkGray;
            this.CmbPosition.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.CmbPosition.IndicatorThickness = 2;
            this.CmbPosition.IsDropdownOpened = false;
            this.CmbPosition.ItemBackColor = System.Drawing.Color.White;
            this.CmbPosition.ItemBorderColor = System.Drawing.Color.White;
            this.CmbPosition.ItemForeColor = System.Drawing.Color.Black;
            this.CmbPosition.ItemHeight = 27;
            this.CmbPosition.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.CmbPosition.ItemHighLightForeColor = System.Drawing.Color.White;
            this.CmbPosition.Items.AddRange(new object[] {
            "Admin",
            "Student Assistant"});
            this.CmbPosition.ItemTopMargin = 3;
            this.CmbPosition.Location = new System.Drawing.Point(77, 469);
            this.CmbPosition.Name = "CmbPosition";
            this.CmbPosition.Size = new System.Drawing.Size(196, 33);
            this.CmbPosition.TabIndex = 12;
            this.CmbPosition.Text = null;
            this.CmbPosition.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.CmbPosition.TextLeftMargin = 5;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel7.Location = new System.Drawing.Point(78, 448);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(43, 15);
            this.bunifuLabel7.TabIndex = 13;
            this.bunifuLabel7.Text = "Position";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // PbProfile
            // 
            this.PbProfile.AllowFocused = false;
            this.PbProfile.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.PbProfile.AutoSizeHeight = false;
            this.PbProfile.BorderRadius = 0;
            this.PbProfile.Image = global::LMS.Properties.Resources.placeholder;
            this.PbProfile.IsCircle = true;
            this.PbProfile.Location = new System.Drawing.Point(348, 71);
            this.PbProfile.Name = "PbProfile";
            this.PbProfile.Size = new System.Drawing.Size(172, 172);
            this.PbProfile.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.PbProfile.TabIndex = 14;
            this.PbProfile.TabStop = false;
            this.PbProfile.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            this.PbProfile.Click += new System.EventHandler(this.PbProfile_Click);
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel8.Location = new System.Drawing.Point(339, 291);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(53, 15);
            this.bunifuLabel8.TabIndex = 15;
            this.bunifuLabel8.Text = "Username";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TxtUsername
            // 
            this.TxtUsername.AcceptsReturn = false;
            this.TxtUsername.AcceptsTab = false;
            this.TxtUsername.AnimationSpeed = 200;
            this.TxtUsername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtUsername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtUsername.AutoSizeHeight = true;
            this.TxtUsername.BackColor = System.Drawing.Color.White;
            this.TxtUsername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtUsername.BackgroundImage")));
            this.TxtUsername.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtUsername.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtUsername.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtUsername.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtUsername.BorderRadius = 1;
            this.TxtUsername.BorderThickness = 1;
            this.TxtUsername.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.TxtUsername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtUsername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtUsername.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtUsername.DefaultText = "";
            this.TxtUsername.FillColor = System.Drawing.Color.White;
            this.TxtUsername.HideSelection = true;
            this.TxtUsername.IconLeft = null;
            this.TxtUsername.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtUsername.IconPadding = 10;
            this.TxtUsername.IconRight = null;
            this.TxtUsername.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtUsername.Lines = new string[0];
            this.TxtUsername.Location = new System.Drawing.Point(339, 312);
            this.TxtUsername.MaxLength = 32767;
            this.TxtUsername.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtUsername.Modified = false;
            this.TxtUsername.Multiline = false;
            this.TxtUsername.Name = "TxtUsername";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtUsername.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtUsername.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtUsername.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtUsername.OnIdleState = stateProperties20;
            this.TxtUsername.Padding = new System.Windows.Forms.Padding(3);
            this.TxtUsername.PasswordChar = '\0';
            this.TxtUsername.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtUsername.PlaceholderText = "Enter Username";
            this.TxtUsername.ReadOnly = false;
            this.TxtUsername.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtUsername.SelectedText = "";
            this.TxtUsername.SelectionLength = 0;
            this.TxtUsername.SelectionStart = 0;
            this.TxtUsername.ShortcutsEnabled = true;
            this.TxtUsername.Size = new System.Drawing.Size(196, 39);
            this.TxtUsername.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtUsername.TabIndex = 16;
            this.TxtUsername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtUsername.TextMarginBottom = 0;
            this.TxtUsername.TextMarginLeft = 3;
            this.TxtUsername.TextMarginTop = 1;
            this.TxtUsername.TextPlaceholder = "Enter Username";
            this.TxtUsername.UseSystemPasswordChar = false;
            this.TxtUsername.WordWrap = true;
            // 
            // TxtPassword
            // 
            this.TxtPassword.AcceptsReturn = false;
            this.TxtPassword.AcceptsTab = false;
            this.TxtPassword.AnimationSpeed = 200;
            this.TxtPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtPassword.AutoSizeHeight = true;
            this.TxtPassword.BackColor = System.Drawing.Color.White;
            this.TxtPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtPassword.BackgroundImage")));
            this.TxtPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtPassword.BorderRadius = 1;
            this.TxtPassword.BorderThickness = 1;
            this.TxtPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.TxtPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtPassword.DefaultText = "";
            this.TxtPassword.FillColor = System.Drawing.Color.White;
            this.TxtPassword.HideSelection = true;
            this.TxtPassword.IconLeft = null;
            this.TxtPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPassword.IconPadding = 10;
            this.TxtPassword.IconRight = null;
            this.TxtPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPassword.Lines = new string[0];
            this.TxtPassword.Location = new System.Drawing.Point(340, 389);
            this.TxtPassword.MaxLength = 32767;
            this.TxtPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtPassword.Modified = false;
            this.TxtPassword.Multiline = false;
            this.TxtPassword.Name = "TxtPassword";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtPassword.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtPassword.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtPassword.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtPassword.OnIdleState = stateProperties24;
            this.TxtPassword.Padding = new System.Windows.Forms.Padding(3);
            this.TxtPassword.PasswordChar = '\0';
            this.TxtPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtPassword.PlaceholderText = "Enter Password";
            this.TxtPassword.ReadOnly = false;
            this.TxtPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtPassword.SelectedText = "";
            this.TxtPassword.SelectionLength = 0;
            this.TxtPassword.SelectionStart = 0;
            this.TxtPassword.ShortcutsEnabled = true;
            this.TxtPassword.Size = new System.Drawing.Size(196, 39);
            this.TxtPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtPassword.TabIndex = 18;
            this.TxtPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtPassword.TextMarginBottom = 0;
            this.TxtPassword.TextMarginLeft = 3;
            this.TxtPassword.TextMarginTop = 1;
            this.TxtPassword.TextPlaceholder = "Enter Password";
            this.TxtPassword.UseSystemPasswordChar = false;
            this.TxtPassword.WordWrap = true;
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.CursorType = null;
            this.bunifuLabel9.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel9.Location = new System.Drawing.Point(339, 368);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(50, 15);
            this.bunifuLabel9.TabIndex = 17;
            this.bunifuLabel9.Text = "Password";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TxtConfirmPassword
            // 
            this.TxtConfirmPassword.AcceptsReturn = false;
            this.TxtConfirmPassword.AcceptsTab = false;
            this.TxtConfirmPassword.AnimationSpeed = 200;
            this.TxtConfirmPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtConfirmPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtConfirmPassword.AutoSizeHeight = true;
            this.TxtConfirmPassword.BackColor = System.Drawing.Color.White;
            this.TxtConfirmPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtConfirmPassword.BackgroundImage")));
            this.TxtConfirmPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtConfirmPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtConfirmPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtConfirmPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtConfirmPassword.BorderRadius = 1;
            this.TxtConfirmPassword.BorderThickness = 1;
            this.TxtConfirmPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.TxtConfirmPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtConfirmPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtConfirmPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtConfirmPassword.DefaultText = "";
            this.TxtConfirmPassword.FillColor = System.Drawing.Color.White;
            this.TxtConfirmPassword.HideSelection = true;
            this.TxtConfirmPassword.IconLeft = null;
            this.TxtConfirmPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtConfirmPassword.IconPadding = 10;
            this.TxtConfirmPassword.IconRight = null;
            this.TxtConfirmPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtConfirmPassword.Lines = new string[0];
            this.TxtConfirmPassword.Location = new System.Drawing.Point(339, 469);
            this.TxtConfirmPassword.MaxLength = 32767;
            this.TxtConfirmPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtConfirmPassword.Modified = false;
            this.TxtConfirmPassword.Multiline = false;
            this.TxtConfirmPassword.Name = "TxtConfirmPassword";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtConfirmPassword.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtConfirmPassword.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtConfirmPassword.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtConfirmPassword.OnIdleState = stateProperties28;
            this.TxtConfirmPassword.Padding = new System.Windows.Forms.Padding(3);
            this.TxtConfirmPassword.PasswordChar = '\0';
            this.TxtConfirmPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtConfirmPassword.PlaceholderText = "Confirm Password";
            this.TxtConfirmPassword.ReadOnly = false;
            this.TxtConfirmPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtConfirmPassword.SelectedText = "";
            this.TxtConfirmPassword.SelectionLength = 0;
            this.TxtConfirmPassword.SelectionStart = 0;
            this.TxtConfirmPassword.ShortcutsEnabled = true;
            this.TxtConfirmPassword.Size = new System.Drawing.Size(196, 39);
            this.TxtConfirmPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtConfirmPassword.TabIndex = 20;
            this.TxtConfirmPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtConfirmPassword.TextMarginBottom = 0;
            this.TxtConfirmPassword.TextMarginLeft = 3;
            this.TxtConfirmPassword.TextMarginTop = 1;
            this.TxtConfirmPassword.TextPlaceholder = "Confirm Password";
            this.TxtConfirmPassword.UseSystemPasswordChar = false;
            this.TxtConfirmPassword.WordWrap = true;
            // 
            // bunifuLabel10
            // 
            this.bunifuLabel10.AllowParentOverrides = false;
            this.bunifuLabel10.AutoEllipsis = false;
            this.bunifuLabel10.CursorType = null;
            this.bunifuLabel10.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel10.Location = new System.Drawing.Point(339, 448);
            this.bunifuLabel10.Name = "bunifuLabel10";
            this.bunifuLabel10.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel10.Size = new System.Drawing.Size(97, 15);
            this.bunifuLabel10.TabIndex = 19;
            this.bunifuLabel10.Text = "Confirm Password";
            this.bunifuLabel10.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel10.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // BtnCancel
            // 
            this.BtnCancel.AllowAnimations = true;
            this.BtnCancel.AllowMouseEffects = true;
            this.BtnCancel.AllowToggling = false;
            this.BtnCancel.AnimationSpeed = 200;
            this.BtnCancel.AutoGenerateColors = false;
            this.BtnCancel.AutoRoundBorders = true;
            this.BtnCancel.AutoSizeLeftIcon = true;
            this.BtnCancel.AutoSizeRightIcon = true;
            this.BtnCancel.BackColor = System.Drawing.Color.Transparent;
            this.BtnCancel.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCancel.BackgroundImage")));
            this.BtnCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancel.ButtonText = "Cancel";
            this.BtnCancel.ButtonTextMarginLeft = 0;
            this.BtnCancel.ColorContrastOnClick = 45;
            this.BtnCancel.ColorContrastOnHover = 45;
            this.BtnCancel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.BtnCancel.CustomizableEdges = borderEdges1;
            this.BtnCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCancel.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnCancel.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCancel.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnCancel.ForeColor = System.Drawing.Color.White;
            this.BtnCancel.IconLeft = null;
            this.BtnCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCancel.IconMarginLeft = 11;
            this.BtnCancel.IconPadding = 10;
            this.BtnCancel.IconRight = null;
            this.BtnCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCancel.IconSize = 25;
            this.BtnCancel.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnCancel.IdleBorderRadius = 0;
            this.BtnCancel.IdleBorderThickness = 0;
            this.BtnCancel.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnCancel.IdleIconLeftImage = null;
            this.BtnCancel.IdleIconRightImage = null;
            this.BtnCancel.IndicateFocus = false;
            this.BtnCancel.Location = new System.Drawing.Point(337, 517);
            this.BtnCancel.Name = "BtnCancel";
            this.BtnCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCancel.OnDisabledState.BorderRadius = 32;
            this.BtnCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancel.OnDisabledState.BorderThickness = 1;
            this.BtnCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCancel.OnDisabledState.IconLeftImage = null;
            this.BtnCancel.OnDisabledState.IconRightImage = null;
            this.BtnCancel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnCancel.onHoverState.BorderRadius = 32;
            this.BtnCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancel.onHoverState.BorderThickness = 1;
            this.BtnCancel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnCancel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCancel.onHoverState.IconLeftImage = null;
            this.BtnCancel.onHoverState.IconRightImage = null;
            this.BtnCancel.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.BtnCancel.OnIdleState.BorderRadius = 32;
            this.BtnCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancel.OnIdleState.BorderThickness = 1;
            this.BtnCancel.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.BtnCancel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCancel.OnIdleState.IconLeftImage = null;
            this.BtnCancel.OnIdleState.IconRightImage = null;
            this.BtnCancel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnCancel.OnPressedState.BorderRadius = 32;
            this.BtnCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancel.OnPressedState.BorderThickness = 1;
            this.BtnCancel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnCancel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCancel.OnPressedState.IconLeftImage = null;
            this.BtnCancel.OnPressedState.IconRightImage = null;
            this.BtnCancel.Size = new System.Drawing.Size(99, 32);
            this.BtnCancel.TabIndex = 21;
            this.BtnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCancel.TextMarginLeft = 0;
            this.BtnCancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCancel.UseDefaultRadiusAndThickness = true;
            // 
            // BtnSave
            // 
            this.BtnSave.AllowAnimations = true;
            this.BtnSave.AllowMouseEffects = true;
            this.BtnSave.AllowToggling = false;
            this.BtnSave.AnimationSpeed = 200;
            this.BtnSave.AutoGenerateColors = false;
            this.BtnSave.AutoRoundBorders = true;
            this.BtnSave.AutoSizeLeftIcon = true;
            this.BtnSave.AutoSizeRightIcon = true;
            this.BtnSave.BackColor = System.Drawing.Color.Transparent;
            this.BtnSave.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnSave.BackgroundImage")));
            this.BtnSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSave.ButtonText = "Save";
            this.BtnSave.ButtonTextMarginLeft = 0;
            this.BtnSave.ColorContrastOnClick = 45;
            this.BtnSave.ColorContrastOnHover = 45;
            this.BtnSave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.BtnSave.CustomizableEdges = borderEdges2;
            this.BtnSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnSave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnSave.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnSave.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnSave.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnSave.ForeColor = System.Drawing.Color.White;
            this.BtnSave.IconLeft = null;
            this.BtnSave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnSave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnSave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnSave.IconMarginLeft = 11;
            this.BtnSave.IconPadding = 10;
            this.BtnSave.IconRight = null;
            this.BtnSave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnSave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnSave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnSave.IconSize = 25;
            this.BtnSave.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnSave.IdleBorderRadius = 0;
            this.BtnSave.IdleBorderThickness = 0;
            this.BtnSave.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnSave.IdleIconLeftImage = null;
            this.BtnSave.IdleIconRightImage = null;
            this.BtnSave.IndicateFocus = false;
            this.BtnSave.Location = new System.Drawing.Point(442, 517);
            this.BtnSave.Name = "BtnSave";
            this.BtnSave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnSave.OnDisabledState.BorderRadius = 32;
            this.BtnSave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSave.OnDisabledState.BorderThickness = 1;
            this.BtnSave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnSave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnSave.OnDisabledState.IconLeftImage = null;
            this.BtnSave.OnDisabledState.IconRightImage = null;
            this.BtnSave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnSave.onHoverState.BorderRadius = 32;
            this.BtnSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSave.onHoverState.BorderThickness = 1;
            this.BtnSave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnSave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnSave.onHoverState.IconLeftImage = null;
            this.BtnSave.onHoverState.IconRightImage = null;
            this.BtnSave.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.BtnSave.OnIdleState.BorderRadius = 32;
            this.BtnSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSave.OnIdleState.BorderThickness = 1;
            this.BtnSave.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.BtnSave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnSave.OnIdleState.IconLeftImage = null;
            this.BtnSave.OnIdleState.IconRightImage = null;
            this.BtnSave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnSave.OnPressedState.BorderRadius = 32;
            this.BtnSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSave.OnPressedState.BorderThickness = 1;
            this.BtnSave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnSave.OnPressedState.IconLeftImage = null;
            this.BtnSave.OnPressedState.IconRightImage = null;
            this.BtnSave.Size = new System.Drawing.Size(99, 32);
            this.BtnSave.TabIndex = 22;
            this.BtnSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnSave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnSave.TextMarginLeft = 0;
            this.BtnSave.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnSave.UseDefaultRadiusAndThickness = true;
            this.BtnSave.Click += new System.EventHandler(this.BtnSave_Click);
            // 
            // FrmAddUser
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(623, 561);
            this.Controls.Add(this.BtnSave);
            this.Controls.Add(this.BtnCancel);
            this.Controls.Add(this.TxtConfirmPassword);
            this.Controls.Add(this.bunifuLabel10);
            this.Controls.Add(this.TxtPassword);
            this.Controls.Add(this.bunifuLabel9);
            this.Controls.Add(this.TxtUsername);
            this.Controls.Add(this.bunifuLabel8);
            this.Controls.Add(this.PbProfile);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.CmbPosition);
            this.Controls.Add(this.TxtEmailAddress);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.TxtContactNo);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.TxtAddress);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.DtpBirthday);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.TxtName);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.bunifuFormControlBox1);
            this.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "FrmAddUser";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FrmAddUser";
            ((System.ComponentModel.ISupportInitialize)(this.PbProfile)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuFormControlBox bunifuFormControlBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox TxtName;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuDatePicker DtpBirthday;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox TxtAddress;
        private Bunifu.UI.WinForms.BunifuTextBox TxtContactNo;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox TxtEmailAddress;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuDropdown CmbPosition;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuPictureBox PbProfile;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuTextBox TxtUsername;
        private Bunifu.UI.WinForms.BunifuTextBox TxtPassword;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuTextBox TxtConfirmPassword;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel10;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCancel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnSave;
    }
}