namespace LMS.View
{
    partial class FrmEditUser
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmEditUser));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuLabel10 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.CmbPosition = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuFormControlBox1 = new Bunifu.UI.WinForms.BunifuFormControlBox();
            this.BtnUpdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.TxtConfirmPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtUsername = new Bunifu.UI.WinForms.BunifuTextBox();
            this.PbProfile = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.TxtEmailAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtContactNo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.DtpBirthday = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.TxtName = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.PbProfile)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuLabel10
            // 
            this.bunifuLabel10.AllowParentOverrides = false;
            this.bunifuLabel10.AutoEllipsis = false;
            this.bunifuLabel10.CursorType = null;
            this.bunifuLabel10.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel10.Location = new System.Drawing.Point(343, 443);
            this.bunifuLabel10.Name = "bunifuLabel10";
            this.bunifuLabel10.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel10.Size = new System.Drawing.Size(97, 15);
            this.bunifuLabel10.TabIndex = 42;
            this.bunifuLabel10.Text = "Confirm Password";
            this.bunifuLabel10.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel10.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.CursorType = null;
            this.bunifuLabel9.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel9.Location = new System.Drawing.Point(343, 363);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(50, 15);
            this.bunifuLabel9.TabIndex = 40;
            this.bunifuLabel9.Text = "Password";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel8.Location = new System.Drawing.Point(343, 286);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(53, 15);
            this.bunifuLabel8.TabIndex = 38;
            this.bunifuLabel8.Text = "Username";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel7.Location = new System.Drawing.Point(82, 443);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(43, 15);
            this.bunifuLabel7.TabIndex = 36;
            this.bunifuLabel7.Text = "Position";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // CmbPosition
            // 
            this.CmbPosition.BackColor = System.Drawing.Color.Transparent;
            this.CmbPosition.BackgroundColor = System.Drawing.Color.White;
            this.CmbPosition.BorderColor = System.Drawing.Color.Silver;
            this.CmbPosition.BorderRadius = 1;
            this.CmbPosition.Color = System.Drawing.Color.Silver;
            this.CmbPosition.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.CmbPosition.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.CmbPosition.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CmbPosition.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.CmbPosition.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.CmbPosition.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.CmbPosition.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.CmbPosition.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.CmbPosition.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.CmbPosition.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.CmbPosition.FillDropDown = true;
            this.CmbPosition.FillIndicator = false;
            this.CmbPosition.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.CmbPosition.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.CmbPosition.ForeColor = System.Drawing.Color.Black;
            this.CmbPosition.FormattingEnabled = true;
            this.CmbPosition.Icon = null;
            this.CmbPosition.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.CmbPosition.IndicatorColor = System.Drawing.Color.DarkGray;
            this.CmbPosition.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.CmbPosition.IndicatorThickness = 2;
            this.CmbPosition.IsDropdownOpened = false;
            this.CmbPosition.ItemBackColor = System.Drawing.Color.White;
            this.CmbPosition.ItemBorderColor = System.Drawing.Color.White;
            this.CmbPosition.ItemForeColor = System.Drawing.Color.Black;
            this.CmbPosition.ItemHeight = 27;
            this.CmbPosition.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.CmbPosition.ItemHighLightForeColor = System.Drawing.Color.White;
            this.CmbPosition.Items.AddRange(new object[] {
            "Admin",
            "Student Assistant"});
            this.CmbPosition.ItemTopMargin = 3;
            this.CmbPosition.Location = new System.Drawing.Point(81, 464);
            this.CmbPosition.Name = "CmbPosition";
            this.CmbPosition.Size = new System.Drawing.Size(196, 33);
            this.CmbPosition.TabIndex = 35;
            this.CmbPosition.Text = null;
            this.CmbPosition.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.CmbPosition.TextLeftMargin = 5;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel6.Location = new System.Drawing.Point(81, 363);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(74, 15);
            this.bunifuLabel6.TabIndex = 33;
            this.bunifuLabel6.Text = "Email Address";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel5.Location = new System.Drawing.Point(81, 286);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(64, 15);
            this.bunifuLabel5.TabIndex = 31;
            this.bunifuLabel5.Text = "Contact No.";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel4.Location = new System.Drawing.Point(81, 211);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(42, 15);
            this.bunifuLabel4.TabIndex = 29;
            this.bunifuLabel4.Text = "Address";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(81, 143);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(44, 15);
            this.bunifuLabel3.TabIndex = 27;
            this.bunifuLabel3.Text = "Birthday";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.Location = new System.Drawing.Point(81, 66);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(35, 15);
            this.bunifuLabel2.TabIndex = 25;
            this.bunifuLabel2.Text = "Name:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(186, 7);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(298, 45);
            this.bunifuLabel1.TabIndex = 24;
            this.bunifuLabel1.Text = "Update Information";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuFormControlBox1
            // 
            this.bunifuFormControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuFormControlBox1.BunifuFormDrag = null;
            this.bunifuFormControlBox1.CloseBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.CloseBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.CloseBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.CloseBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.CloseBoxOptions.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.CloseBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.CloseBoxOptions.Icon")));
            this.bunifuFormControlBox1.CloseBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.CloseBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.CloseBoxOptions.IconHoverColor = System.Drawing.Color.White;
            this.bunifuFormControlBox1.CloseBoxOptions.IconPressedColor = System.Drawing.Color.White;
            this.bunifuFormControlBox1.CloseBoxOptions.IconSize = new System.Drawing.Size(18, 18);
            this.bunifuFormControlBox1.CloseBoxOptions.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.HelpBox = false;
            this.bunifuFormControlBox1.HelpBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.HelpBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.HelpBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.HelpBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.HelpBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.HelpBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.HelpBoxOptions.Icon")));
            this.bunifuFormControlBox1.HelpBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.HelpBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconSize = new System.Drawing.Size(22, 22);
            this.bunifuFormControlBox1.HelpBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Location = new System.Drawing.Point(509, 1);
            this.bunifuFormControlBox1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuFormControlBox1.MaximizeBox = false;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconAlt = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.IconAlt")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconSize = new System.Drawing.Size(16, 16);
            this.bunifuFormControlBox1.MaximizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.MinimizeBox = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MinimizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconSize = new System.Drawing.Size(14, 14);
            this.bunifuFormControlBox1.MinimizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Name = "bunifuFormControlBox1";
            this.bunifuFormControlBox1.ShowDesignBorders = false;
            this.bunifuFormControlBox1.Size = new System.Drawing.Size(115, 22);
            this.bunifuFormControlBox1.TabIndex = 23;
            // 
            // BtnUpdate
            // 
            this.BtnUpdate.AllowAnimations = true;
            this.BtnUpdate.AllowMouseEffects = true;
            this.BtnUpdate.AllowToggling = false;
            this.BtnUpdate.AnimationSpeed = 200;
            this.BtnUpdate.AutoGenerateColors = false;
            this.BtnUpdate.AutoRoundBorders = true;
            this.BtnUpdate.AutoSizeLeftIcon = true;
            this.BtnUpdate.AutoSizeRightIcon = true;
            this.BtnUpdate.BackColor = System.Drawing.Color.Transparent;
            this.BtnUpdate.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnUpdate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnUpdate.BackgroundImage")));
            this.BtnUpdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdate.ButtonText = "Update";
            this.BtnUpdate.ButtonTextMarginLeft = 0;
            this.BtnUpdate.ColorContrastOnClick = 45;
            this.BtnUpdate.ColorContrastOnHover = 45;
            this.BtnUpdate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.BtnUpdate.CustomizableEdges = borderEdges3;
            this.BtnUpdate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnUpdate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnUpdate.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnUpdate.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnUpdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnUpdate.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnUpdate.ForeColor = System.Drawing.Color.White;
            this.BtnUpdate.IconLeft = null;
            this.BtnUpdate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnUpdate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnUpdate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnUpdate.IconMarginLeft = 11;
            this.BtnUpdate.IconPadding = 10;
            this.BtnUpdate.IconRight = null;
            this.BtnUpdate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnUpdate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnUpdate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnUpdate.IconSize = 25;
            this.BtnUpdate.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnUpdate.IdleBorderRadius = 0;
            this.BtnUpdate.IdleBorderThickness = 0;
            this.BtnUpdate.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnUpdate.IdleIconLeftImage = null;
            this.BtnUpdate.IdleIconRightImage = null;
            this.BtnUpdate.IndicateFocus = false;
            this.BtnUpdate.Location = new System.Drawing.Point(446, 512);
            this.BtnUpdate.Name = "BtnUpdate";
            this.BtnUpdate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnUpdate.OnDisabledState.BorderRadius = 32;
            this.BtnUpdate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdate.OnDisabledState.BorderThickness = 1;
            this.BtnUpdate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnUpdate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnUpdate.OnDisabledState.IconLeftImage = null;
            this.BtnUpdate.OnDisabledState.IconRightImage = null;
            this.BtnUpdate.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnUpdate.onHoverState.BorderRadius = 32;
            this.BtnUpdate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdate.onHoverState.BorderThickness = 1;
            this.BtnUpdate.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnUpdate.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnUpdate.onHoverState.IconLeftImage = null;
            this.BtnUpdate.onHoverState.IconRightImage = null;
            this.BtnUpdate.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.BtnUpdate.OnIdleState.BorderRadius = 32;
            this.BtnUpdate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdate.OnIdleState.BorderThickness = 1;
            this.BtnUpdate.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.BtnUpdate.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnUpdate.OnIdleState.IconLeftImage = null;
            this.BtnUpdate.OnIdleState.IconRightImage = null;
            this.BtnUpdate.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnUpdate.OnPressedState.BorderRadius = 32;
            this.BtnUpdate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdate.OnPressedState.BorderThickness = 1;
            this.BtnUpdate.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnUpdate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnUpdate.OnPressedState.IconLeftImage = null;
            this.BtnUpdate.OnPressedState.IconRightImage = null;
            this.BtnUpdate.Size = new System.Drawing.Size(99, 32);
            this.BtnUpdate.TabIndex = 45;
            this.BtnUpdate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnUpdate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnUpdate.TextMarginLeft = 0;
            this.BtnUpdate.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnUpdate.UseDefaultRadiusAndThickness = true;
            this.BtnUpdate.Click += new System.EventHandler(this.BtnUpdate_Click);
            // 
            // BtnCancel
            // 
            this.BtnCancel.AllowAnimations = true;
            this.BtnCancel.AllowMouseEffects = true;
            this.BtnCancel.AllowToggling = false;
            this.BtnCancel.AnimationSpeed = 200;
            this.BtnCancel.AutoGenerateColors = false;
            this.BtnCancel.AutoRoundBorders = true;
            this.BtnCancel.AutoSizeLeftIcon = true;
            this.BtnCancel.AutoSizeRightIcon = true;
            this.BtnCancel.BackColor = System.Drawing.Color.Transparent;
            this.BtnCancel.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCancel.BackgroundImage")));
            this.BtnCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancel.ButtonText = "Cancel";
            this.BtnCancel.ButtonTextMarginLeft = 0;
            this.BtnCancel.ColorContrastOnClick = 45;
            this.BtnCancel.ColorContrastOnHover = 45;
            this.BtnCancel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.BtnCancel.CustomizableEdges = borderEdges4;
            this.BtnCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCancel.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnCancel.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCancel.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnCancel.ForeColor = System.Drawing.Color.White;
            this.BtnCancel.IconLeft = null;
            this.BtnCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCancel.IconMarginLeft = 11;
            this.BtnCancel.IconPadding = 10;
            this.BtnCancel.IconRight = null;
            this.BtnCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCancel.IconSize = 25;
            this.BtnCancel.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnCancel.IdleBorderRadius = 0;
            this.BtnCancel.IdleBorderThickness = 0;
            this.BtnCancel.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnCancel.IdleIconLeftImage = null;
            this.BtnCancel.IdleIconRightImage = null;
            this.BtnCancel.IndicateFocus = false;
            this.BtnCancel.Location = new System.Drawing.Point(341, 512);
            this.BtnCancel.Name = "BtnCancel";
            this.BtnCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCancel.OnDisabledState.BorderRadius = 32;
            this.BtnCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancel.OnDisabledState.BorderThickness = 1;
            this.BtnCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCancel.OnDisabledState.IconLeftImage = null;
            this.BtnCancel.OnDisabledState.IconRightImage = null;
            this.BtnCancel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnCancel.onHoverState.BorderRadius = 32;
            this.BtnCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancel.onHoverState.BorderThickness = 1;
            this.BtnCancel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnCancel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCancel.onHoverState.IconLeftImage = null;
            this.BtnCancel.onHoverState.IconRightImage = null;
            this.BtnCancel.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.BtnCancel.OnIdleState.BorderRadius = 32;
            this.BtnCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancel.OnIdleState.BorderThickness = 1;
            this.BtnCancel.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.BtnCancel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCancel.OnIdleState.IconLeftImage = null;
            this.BtnCancel.OnIdleState.IconRightImage = null;
            this.BtnCancel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnCancel.OnPressedState.BorderRadius = 32;
            this.BtnCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancel.OnPressedState.BorderThickness = 1;
            this.BtnCancel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnCancel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCancel.OnPressedState.IconLeftImage = null;
            this.BtnCancel.OnPressedState.IconRightImage = null;
            this.BtnCancel.Size = new System.Drawing.Size(99, 32);
            this.BtnCancel.TabIndex = 44;
            this.BtnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCancel.TextMarginLeft = 0;
            this.BtnCancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCancel.UseDefaultRadiusAndThickness = true;
            // 
            // TxtConfirmPassword
            // 
            this.TxtConfirmPassword.AcceptsReturn = false;
            this.TxtConfirmPassword.AcceptsTab = false;
            this.TxtConfirmPassword.AnimationSpeed = 200;
            this.TxtConfirmPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtConfirmPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtConfirmPassword.AutoSizeHeight = true;
            this.TxtConfirmPassword.BackColor = System.Drawing.Color.White;
            this.TxtConfirmPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtConfirmPassword.BackgroundImage")));
            this.TxtConfirmPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtConfirmPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtConfirmPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtConfirmPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtConfirmPassword.BorderRadius = 1;
            this.TxtConfirmPassword.BorderThickness = 1;
            this.TxtConfirmPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.TxtConfirmPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtConfirmPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtConfirmPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtConfirmPassword.DefaultText = "";
            this.TxtConfirmPassword.FillColor = System.Drawing.Color.White;
            this.TxtConfirmPassword.HideSelection = true;
            this.TxtConfirmPassword.IconLeft = null;
            this.TxtConfirmPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtConfirmPassword.IconPadding = 10;
            this.TxtConfirmPassword.IconRight = null;
            this.TxtConfirmPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtConfirmPassword.Lines = new string[0];
            this.TxtConfirmPassword.Location = new System.Drawing.Point(343, 464);
            this.TxtConfirmPassword.MaxLength = 32767;
            this.TxtConfirmPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtConfirmPassword.Modified = false;
            this.TxtConfirmPassword.Multiline = false;
            this.TxtConfirmPassword.Name = "TxtConfirmPassword";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtConfirmPassword.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtConfirmPassword.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtConfirmPassword.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtConfirmPassword.OnIdleState = stateProperties32;
            this.TxtConfirmPassword.Padding = new System.Windows.Forms.Padding(3);
            this.TxtConfirmPassword.PasswordChar = '\0';
            this.TxtConfirmPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtConfirmPassword.PlaceholderText = "Confirm Password";
            this.TxtConfirmPassword.ReadOnly = false;
            this.TxtConfirmPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtConfirmPassword.SelectedText = "";
            this.TxtConfirmPassword.SelectionLength = 0;
            this.TxtConfirmPassword.SelectionStart = 0;
            this.TxtConfirmPassword.ShortcutsEnabled = true;
            this.TxtConfirmPassword.Size = new System.Drawing.Size(196, 39);
            this.TxtConfirmPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtConfirmPassword.TabIndex = 43;
            this.TxtConfirmPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtConfirmPassword.TextMarginBottom = 0;
            this.TxtConfirmPassword.TextMarginLeft = 3;
            this.TxtConfirmPassword.TextMarginTop = 1;
            this.TxtConfirmPassword.TextPlaceholder = "Confirm Password";
            this.TxtConfirmPassword.UseSystemPasswordChar = false;
            this.TxtConfirmPassword.WordWrap = true;
            // 
            // TxtPassword
            // 
            this.TxtPassword.AcceptsReturn = false;
            this.TxtPassword.AcceptsTab = false;
            this.TxtPassword.AnimationSpeed = 200;
            this.TxtPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtPassword.AutoSizeHeight = true;
            this.TxtPassword.BackColor = System.Drawing.Color.White;
            this.TxtPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtPassword.BackgroundImage")));
            this.TxtPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtPassword.BorderRadius = 1;
            this.TxtPassword.BorderThickness = 1;
            this.TxtPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.TxtPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtPassword.DefaultText = "";
            this.TxtPassword.FillColor = System.Drawing.Color.White;
            this.TxtPassword.HideSelection = true;
            this.TxtPassword.IconLeft = null;
            this.TxtPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPassword.IconPadding = 10;
            this.TxtPassword.IconRight = null;
            this.TxtPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPassword.Lines = new string[0];
            this.TxtPassword.Location = new System.Drawing.Point(344, 384);
            this.TxtPassword.MaxLength = 32767;
            this.TxtPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtPassword.Modified = false;
            this.TxtPassword.Multiline = false;
            this.TxtPassword.Name = "TxtPassword";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtPassword.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtPassword.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtPassword.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtPassword.OnIdleState = stateProperties36;
            this.TxtPassword.Padding = new System.Windows.Forms.Padding(3);
            this.TxtPassword.PasswordChar = '\0';
            this.TxtPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtPassword.PlaceholderText = "Enter Password";
            this.TxtPassword.ReadOnly = false;
            this.TxtPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtPassword.SelectedText = "";
            this.TxtPassword.SelectionLength = 0;
            this.TxtPassword.SelectionStart = 0;
            this.TxtPassword.ShortcutsEnabled = true;
            this.TxtPassword.Size = new System.Drawing.Size(196, 39);
            this.TxtPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtPassword.TabIndex = 41;
            this.TxtPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtPassword.TextMarginBottom = 0;
            this.TxtPassword.TextMarginLeft = 3;
            this.TxtPassword.TextMarginTop = 1;
            this.TxtPassword.TextPlaceholder = "Enter Password";
            this.TxtPassword.UseSystemPasswordChar = false;
            this.TxtPassword.WordWrap = true;
            // 
            // TxtUsername
            // 
            this.TxtUsername.AcceptsReturn = false;
            this.TxtUsername.AcceptsTab = false;
            this.TxtUsername.AnimationSpeed = 200;
            this.TxtUsername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtUsername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtUsername.AutoSizeHeight = true;
            this.TxtUsername.BackColor = System.Drawing.Color.White;
            this.TxtUsername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtUsername.BackgroundImage")));
            this.TxtUsername.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtUsername.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtUsername.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtUsername.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtUsername.BorderRadius = 1;
            this.TxtUsername.BorderThickness = 1;
            this.TxtUsername.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.TxtUsername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtUsername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtUsername.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtUsername.DefaultText = "";
            this.TxtUsername.FillColor = System.Drawing.Color.White;
            this.TxtUsername.HideSelection = true;
            this.TxtUsername.IconLeft = null;
            this.TxtUsername.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtUsername.IconPadding = 10;
            this.TxtUsername.IconRight = null;
            this.TxtUsername.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtUsername.Lines = new string[0];
            this.TxtUsername.Location = new System.Drawing.Point(343, 307);
            this.TxtUsername.MaxLength = 32767;
            this.TxtUsername.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtUsername.Modified = false;
            this.TxtUsername.Multiline = false;
            this.TxtUsername.Name = "TxtUsername";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtUsername.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtUsername.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtUsername.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtUsername.OnIdleState = stateProperties40;
            this.TxtUsername.Padding = new System.Windows.Forms.Padding(3);
            this.TxtUsername.PasswordChar = '\0';
            this.TxtUsername.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtUsername.PlaceholderText = "Enter Username";
            this.TxtUsername.ReadOnly = false;
            this.TxtUsername.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtUsername.SelectedText = "";
            this.TxtUsername.SelectionLength = 0;
            this.TxtUsername.SelectionStart = 0;
            this.TxtUsername.ShortcutsEnabled = true;
            this.TxtUsername.Size = new System.Drawing.Size(196, 39);
            this.TxtUsername.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtUsername.TabIndex = 39;
            this.TxtUsername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtUsername.TextMarginBottom = 0;
            this.TxtUsername.TextMarginLeft = 3;
            this.TxtUsername.TextMarginTop = 1;
            this.TxtUsername.TextPlaceholder = "Enter Username";
            this.TxtUsername.UseSystemPasswordChar = false;
            this.TxtUsername.WordWrap = true;
            // 
            // PbProfile
            // 
            this.PbProfile.AllowFocused = false;
            this.PbProfile.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.PbProfile.AutoSizeHeight = false;
            this.PbProfile.BorderRadius = 0;
            this.PbProfile.Image = global::LMS.Properties.Resources.placeholder;
            this.PbProfile.IsCircle = true;
            this.PbProfile.Location = new System.Drawing.Point(344, 88);
            this.PbProfile.Name = "PbProfile";
            this.PbProfile.Size = new System.Drawing.Size(172, 172);
            this.PbProfile.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.PbProfile.TabIndex = 37;
            this.PbProfile.TabStop = false;
            this.PbProfile.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            this.PbProfile.Click += new System.EventHandler(this.PbProfile_Click);
            // 
            // TxtEmailAddress
            // 
            this.TxtEmailAddress.AcceptsReturn = false;
            this.TxtEmailAddress.AcceptsTab = false;
            this.TxtEmailAddress.AnimationSpeed = 200;
            this.TxtEmailAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtEmailAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtEmailAddress.AutoSizeHeight = true;
            this.TxtEmailAddress.BackColor = System.Drawing.Color.White;
            this.TxtEmailAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtEmailAddress.BackgroundImage")));
            this.TxtEmailAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtEmailAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtEmailAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtEmailAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtEmailAddress.BorderRadius = 1;
            this.TxtEmailAddress.BorderThickness = 1;
            this.TxtEmailAddress.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.TxtEmailAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtEmailAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtEmailAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtEmailAddress.DefaultText = "";
            this.TxtEmailAddress.FillColor = System.Drawing.Color.White;
            this.TxtEmailAddress.HideSelection = true;
            this.TxtEmailAddress.IconLeft = null;
            this.TxtEmailAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtEmailAddress.IconPadding = 10;
            this.TxtEmailAddress.IconRight = null;
            this.TxtEmailAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtEmailAddress.Lines = new string[0];
            this.TxtEmailAddress.Location = new System.Drawing.Point(81, 384);
            this.TxtEmailAddress.MaxLength = 32767;
            this.TxtEmailAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtEmailAddress.Modified = false;
            this.TxtEmailAddress.Multiline = false;
            this.TxtEmailAddress.Name = "TxtEmailAddress";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtEmailAddress.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtEmailAddress.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtEmailAddress.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtEmailAddress.OnIdleState = stateProperties44;
            this.TxtEmailAddress.Padding = new System.Windows.Forms.Padding(3);
            this.TxtEmailAddress.PasswordChar = '\0';
            this.TxtEmailAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtEmailAddress.PlaceholderText = "Enter Email Address";
            this.TxtEmailAddress.ReadOnly = false;
            this.TxtEmailAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtEmailAddress.SelectedText = "";
            this.TxtEmailAddress.SelectionLength = 0;
            this.TxtEmailAddress.SelectionStart = 0;
            this.TxtEmailAddress.ShortcutsEnabled = true;
            this.TxtEmailAddress.Size = new System.Drawing.Size(196, 39);
            this.TxtEmailAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtEmailAddress.TabIndex = 34;
            this.TxtEmailAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtEmailAddress.TextMarginBottom = 0;
            this.TxtEmailAddress.TextMarginLeft = 3;
            this.TxtEmailAddress.TextMarginTop = 1;
            this.TxtEmailAddress.TextPlaceholder = "Enter Email Address";
            this.TxtEmailAddress.UseSystemPasswordChar = false;
            this.TxtEmailAddress.WordWrap = true;
            // 
            // TxtContactNo
            // 
            this.TxtContactNo.AcceptsReturn = false;
            this.TxtContactNo.AcceptsTab = false;
            this.TxtContactNo.AnimationSpeed = 200;
            this.TxtContactNo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtContactNo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtContactNo.AutoSizeHeight = true;
            this.TxtContactNo.BackColor = System.Drawing.Color.White;
            this.TxtContactNo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtContactNo.BackgroundImage")));
            this.TxtContactNo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtContactNo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtContactNo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtContactNo.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtContactNo.BorderRadius = 1;
            this.TxtContactNo.BorderThickness = 1;
            this.TxtContactNo.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.TxtContactNo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtContactNo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtContactNo.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtContactNo.DefaultText = "";
            this.TxtContactNo.FillColor = System.Drawing.Color.White;
            this.TxtContactNo.HideSelection = true;
            this.TxtContactNo.IconLeft = null;
            this.TxtContactNo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtContactNo.IconPadding = 10;
            this.TxtContactNo.IconRight = null;
            this.TxtContactNo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtContactNo.Lines = new string[0];
            this.TxtContactNo.Location = new System.Drawing.Point(81, 307);
            this.TxtContactNo.MaxLength = 32767;
            this.TxtContactNo.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtContactNo.Modified = false;
            this.TxtContactNo.Multiline = false;
            this.TxtContactNo.Name = "TxtContactNo";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtContactNo.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtContactNo.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtContactNo.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtContactNo.OnIdleState = stateProperties48;
            this.TxtContactNo.Padding = new System.Windows.Forms.Padding(3);
            this.TxtContactNo.PasswordChar = '\0';
            this.TxtContactNo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtContactNo.PlaceholderText = "Enter Contact No.";
            this.TxtContactNo.ReadOnly = false;
            this.TxtContactNo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtContactNo.SelectedText = "";
            this.TxtContactNo.SelectionLength = 0;
            this.TxtContactNo.SelectionStart = 0;
            this.TxtContactNo.ShortcutsEnabled = true;
            this.TxtContactNo.Size = new System.Drawing.Size(196, 39);
            this.TxtContactNo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtContactNo.TabIndex = 32;
            this.TxtContactNo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtContactNo.TextMarginBottom = 0;
            this.TxtContactNo.TextMarginLeft = 3;
            this.TxtContactNo.TextMarginTop = 1;
            this.TxtContactNo.TextPlaceholder = "Enter Contact No.";
            this.TxtContactNo.UseSystemPasswordChar = false;
            this.TxtContactNo.WordWrap = true;
            // 
            // TxtAddress
            // 
            this.TxtAddress.AcceptsReturn = false;
            this.TxtAddress.AcceptsTab = false;
            this.TxtAddress.AnimationSpeed = 200;
            this.TxtAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtAddress.AutoSizeHeight = true;
            this.TxtAddress.BackColor = System.Drawing.Color.White;
            this.TxtAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtAddress.BackgroundImage")));
            this.TxtAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtAddress.BorderRadius = 1;
            this.TxtAddress.BorderThickness = 1;
            this.TxtAddress.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.TxtAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtAddress.DefaultText = "";
            this.TxtAddress.FillColor = System.Drawing.Color.White;
            this.TxtAddress.HideSelection = true;
            this.TxtAddress.IconLeft = null;
            this.TxtAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtAddress.IconPadding = 10;
            this.TxtAddress.IconRight = null;
            this.TxtAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtAddress.Lines = new string[0];
            this.TxtAddress.Location = new System.Drawing.Point(81, 232);
            this.TxtAddress.MaxLength = 32767;
            this.TxtAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtAddress.Modified = false;
            this.TxtAddress.Multiline = false;
            this.TxtAddress.Name = "TxtAddress";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtAddress.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtAddress.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtAddress.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtAddress.OnIdleState = stateProperties52;
            this.TxtAddress.Padding = new System.Windows.Forms.Padding(3);
            this.TxtAddress.PasswordChar = '\0';
            this.TxtAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtAddress.PlaceholderText = "Enter Address";
            this.TxtAddress.ReadOnly = false;
            this.TxtAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtAddress.SelectedText = "";
            this.TxtAddress.SelectionLength = 0;
            this.TxtAddress.SelectionStart = 0;
            this.TxtAddress.ShortcutsEnabled = true;
            this.TxtAddress.Size = new System.Drawing.Size(196, 39);
            this.TxtAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtAddress.TabIndex = 30;
            this.TxtAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtAddress.TextMarginBottom = 0;
            this.TxtAddress.TextMarginLeft = 3;
            this.TxtAddress.TextMarginTop = 1;
            this.TxtAddress.TextPlaceholder = "Enter Address";
            this.TxtAddress.UseSystemPasswordChar = false;
            this.TxtAddress.WordWrap = true;
            // 
            // DtpBirthday
            // 
            this.DtpBirthday.BackColor = System.Drawing.Color.Transparent;
            this.DtpBirthday.BorderColor = System.Drawing.Color.Silver;
            this.DtpBirthday.BorderRadius = 1;
            this.DtpBirthday.Color = System.Drawing.Color.Silver;
            this.DtpBirthday.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.DtpBirthday.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.DtpBirthday.DisabledColor = System.Drawing.Color.Gray;
            this.DtpBirthday.DisplayWeekNumbers = false;
            this.DtpBirthday.DPHeight = 0;
            this.DtpBirthday.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.DtpBirthday.FillDatePicker = false;
            this.DtpBirthday.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.DtpBirthday.ForeColor = System.Drawing.Color.Black;
            this.DtpBirthday.Icon = ((System.Drawing.Image)(resources.GetObject("DtpBirthday.Icon")));
            this.DtpBirthday.IconColor = System.Drawing.Color.Green;
            this.DtpBirthday.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.DtpBirthday.LeftTextMargin = 5;
            this.DtpBirthday.Location = new System.Drawing.Point(81, 164);
            this.DtpBirthday.MinimumSize = new System.Drawing.Size(4, 32);
            this.DtpBirthday.Name = "DtpBirthday";
            this.DtpBirthday.Size = new System.Drawing.Size(196, 32);
            this.DtpBirthday.TabIndex = 28;
            this.DtpBirthday.Value = new System.DateTime(2024, 10, 16, 20, 3, 0, 0);
            // 
            // TxtName
            // 
            this.TxtName.AcceptsReturn = false;
            this.TxtName.AcceptsTab = false;
            this.TxtName.AnimationSpeed = 200;
            this.TxtName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtName.AutoSizeHeight = true;
            this.TxtName.BackColor = System.Drawing.Color.White;
            this.TxtName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtName.BackgroundImage")));
            this.TxtName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtName.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtName.BorderRadius = 1;
            this.TxtName.BorderThickness = 1;
            this.TxtName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.TxtName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtName.DefaultText = "";
            this.TxtName.FillColor = System.Drawing.Color.White;
            this.TxtName.HideSelection = true;
            this.TxtName.IconLeft = null;
            this.TxtName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtName.IconPadding = 10;
            this.TxtName.IconRight = null;
            this.TxtName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtName.Lines = new string[0];
            this.TxtName.Location = new System.Drawing.Point(81, 88);
            this.TxtName.MaxLength = 32767;
            this.TxtName.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtName.Modified = false;
            this.TxtName.Multiline = false;
            this.TxtName.Name = "TxtName";
            stateProperties53.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtName.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtName.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtName.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Silver;
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtName.OnIdleState = stateProperties56;
            this.TxtName.Padding = new System.Windows.Forms.Padding(3);
            this.TxtName.PasswordChar = '\0';
            this.TxtName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtName.PlaceholderText = "Enter Name";
            this.TxtName.ReadOnly = false;
            this.TxtName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtName.SelectedText = "";
            this.TxtName.SelectionLength = 0;
            this.TxtName.SelectionStart = 0;
            this.TxtName.ShortcutsEnabled = true;
            this.TxtName.Size = new System.Drawing.Size(196, 39);
            this.TxtName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TxtName.TabIndex = 26;
            this.TxtName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtName.TextMarginBottom = 0;
            this.TxtName.TextMarginLeft = 3;
            this.TxtName.TextMarginTop = 1;
            this.TxtName.TextPlaceholder = "Enter Name";
            this.TxtName.UseSystemPasswordChar = false;
            this.TxtName.WordWrap = true;
            // 
            // FrmEditUser
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(623, 561);
            this.Controls.Add(this.BtnUpdate);
            this.Controls.Add(this.BtnCancel);
            this.Controls.Add(this.TxtConfirmPassword);
            this.Controls.Add(this.bunifuLabel10);
            this.Controls.Add(this.TxtPassword);
            this.Controls.Add(this.bunifuLabel9);
            this.Controls.Add(this.TxtUsername);
            this.Controls.Add(this.bunifuLabel8);
            this.Controls.Add(this.PbProfile);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.CmbPosition);
            this.Controls.Add(this.TxtEmailAddress);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.TxtContactNo);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.TxtAddress);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.DtpBirthday);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.TxtName);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.bunifuFormControlBox1);
            this.Name = "FrmEditUser";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FrmEditUser";
            ((System.ComponentModel.ISupportInitialize)(this.PbProfile)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnUpdate;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCancel;
        private Bunifu.UI.WinForms.BunifuTextBox TxtConfirmPassword;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel10;
        private Bunifu.UI.WinForms.BunifuTextBox TxtPassword;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuTextBox TxtUsername;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuPictureBox PbProfile;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuDropdown CmbPosition;
        private Bunifu.UI.WinForms.BunifuTextBox TxtEmailAddress;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox TxtContactNo;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox TxtAddress;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuDatePicker DtpBirthday;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox TxtName;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuFormControlBox bunifuFormControlBox1;
    }
}