namespace LMS.View
{
    partial class FrmTransactions
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmTransactions));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.BtnExportPdf = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnExportExcel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuDatePicker2 = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuDatePicker1 = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.BtnThisMonth = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnCustomDate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnLast3Days = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnThisWeek = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.panelTransactions = new Bunifu.UI.WinForms.BunifuPanel();
            this.DropDownSortByDate = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuShadowPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.BorderRadius = 1;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.Controls.Add(this.BtnExportPdf);
            this.bunifuShadowPanel1.Controls.Add(this.BtnExportExcel);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuDatePicker2);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuDatePicker1);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuShadowPanel1.Controls.Add(this.BtnThisMonth);
            this.bunifuShadowPanel1.Controls.Add(this.BtnCustomDate);
            this.bunifuShadowPanel1.Controls.Add(this.BtnLast3Days);
            this.bunifuShadowPanel1.Controls.Add(this.BtnThisWeek);
            this.bunifuShadowPanel1.Controls.Add(this.DropDownSortByDate);
            this.bunifuShadowPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 5;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.ForwardDiagonal;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(908, 165);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 0;
            // 
            // BtnExportPdf
            // 
            this.BtnExportPdf.AllowAnimations = true;
            this.BtnExportPdf.AllowMouseEffects = true;
            this.BtnExportPdf.AllowToggling = false;
            this.BtnExportPdf.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnExportPdf.AnimationSpeed = 200;
            this.BtnExportPdf.AutoGenerateColors = false;
            this.BtnExportPdf.AutoRoundBorders = false;
            this.BtnExportPdf.AutoSizeLeftIcon = true;
            this.BtnExportPdf.AutoSizeRightIcon = true;
            this.BtnExportPdf.BackColor = System.Drawing.Color.Transparent;
            this.BtnExportPdf.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnExportPdf.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnExportPdf.BackgroundImage")));
            this.BtnExportPdf.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnExportPdf.ButtonText = "Export as PDF";
            this.BtnExportPdf.ButtonTextMarginLeft = 0;
            this.BtnExportPdf.ColorContrastOnClick = 45;
            this.BtnExportPdf.ColorContrastOnHover = 45;
            this.BtnExportPdf.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.BtnExportPdf.CustomizableEdges = borderEdges1;
            this.BtnExportPdf.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnExportPdf.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnExportPdf.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnExportPdf.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnExportPdf.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnExportPdf.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnExportPdf.ForeColor = System.Drawing.Color.White;
            this.BtnExportPdf.IconLeft = null;
            this.BtnExportPdf.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnExportPdf.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnExportPdf.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnExportPdf.IconMarginLeft = 11;
            this.BtnExportPdf.IconPadding = 10;
            this.BtnExportPdf.IconRight = null;
            this.BtnExportPdf.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnExportPdf.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnExportPdf.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnExportPdf.IconSize = 25;
            this.BtnExportPdf.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnExportPdf.IdleBorderRadius = 0;
            this.BtnExportPdf.IdleBorderThickness = 0;
            this.BtnExportPdf.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnExportPdf.IdleIconLeftImage = null;
            this.BtnExportPdf.IdleIconRightImage = null;
            this.BtnExportPdf.IndicateFocus = false;
            this.BtnExportPdf.Location = new System.Drawing.Point(632, 102);
            this.BtnExportPdf.Name = "BtnExportPdf";
            this.BtnExportPdf.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnExportPdf.OnDisabledState.BorderRadius = 1;
            this.BtnExportPdf.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnExportPdf.OnDisabledState.BorderThickness = 1;
            this.BtnExportPdf.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnExportPdf.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnExportPdf.OnDisabledState.IconLeftImage = null;
            this.BtnExportPdf.OnDisabledState.IconRightImage = null;
            this.BtnExportPdf.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnExportPdf.onHoverState.BorderRadius = 1;
            this.BtnExportPdf.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnExportPdf.onHoverState.BorderThickness = 1;
            this.BtnExportPdf.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnExportPdf.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnExportPdf.onHoverState.IconLeftImage = null;
            this.BtnExportPdf.onHoverState.IconRightImage = null;
            this.BtnExportPdf.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.BtnExportPdf.OnIdleState.BorderRadius = 1;
            this.BtnExportPdf.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnExportPdf.OnIdleState.BorderThickness = 1;
            this.BtnExportPdf.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.BtnExportPdf.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnExportPdf.OnIdleState.IconLeftImage = null;
            this.BtnExportPdf.OnIdleState.IconRightImage = null;
            this.BtnExportPdf.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnExportPdf.OnPressedState.BorderRadius = 1;
            this.BtnExportPdf.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnExportPdf.OnPressedState.BorderThickness = 1;
            this.BtnExportPdf.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnExportPdf.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnExportPdf.OnPressedState.IconLeftImage = null;
            this.BtnExportPdf.OnPressedState.IconRightImage = null;
            this.BtnExportPdf.Size = new System.Drawing.Size(117, 39);
            this.BtnExportPdf.TabIndex = 10;
            this.BtnExportPdf.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnExportPdf.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnExportPdf.TextMarginLeft = 0;
            this.BtnExportPdf.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnExportPdf.UseDefaultRadiusAndThickness = true;
            this.BtnExportPdf.Click += new System.EventHandler(this.BtnExportPdf_Click);
            // 
            // BtnExportExcel
            // 
            this.BtnExportExcel.AllowAnimations = true;
            this.BtnExportExcel.AllowMouseEffects = true;
            this.BtnExportExcel.AllowToggling = false;
            this.BtnExportExcel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnExportExcel.AnimationSpeed = 200;
            this.BtnExportExcel.AutoGenerateColors = false;
            this.BtnExportExcel.AutoRoundBorders = false;
            this.BtnExportExcel.AutoSizeLeftIcon = true;
            this.BtnExportExcel.AutoSizeRightIcon = true;
            this.BtnExportExcel.BackColor = System.Drawing.Color.Transparent;
            this.BtnExportExcel.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnExportExcel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnExportExcel.BackgroundImage")));
            this.BtnExportExcel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnExportExcel.ButtonText = "Export to Excel";
            this.BtnExportExcel.ButtonTextMarginLeft = 0;
            this.BtnExportExcel.ColorContrastOnClick = 45;
            this.BtnExportExcel.ColorContrastOnHover = 45;
            this.BtnExportExcel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.BtnExportExcel.CustomizableEdges = borderEdges2;
            this.BtnExportExcel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnExportExcel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnExportExcel.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnExportExcel.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnExportExcel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnExportExcel.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnExportExcel.ForeColor = System.Drawing.Color.White;
            this.BtnExportExcel.IconLeft = null;
            this.BtnExportExcel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnExportExcel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnExportExcel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnExportExcel.IconMarginLeft = 11;
            this.BtnExportExcel.IconPadding = 10;
            this.BtnExportExcel.IconRight = null;
            this.BtnExportExcel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnExportExcel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnExportExcel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnExportExcel.IconSize = 25;
            this.BtnExportExcel.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnExportExcel.IdleBorderRadius = 0;
            this.BtnExportExcel.IdleBorderThickness = 0;
            this.BtnExportExcel.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnExportExcel.IdleIconLeftImage = null;
            this.BtnExportExcel.IdleIconRightImage = null;
            this.BtnExportExcel.IndicateFocus = false;
            this.BtnExportExcel.Location = new System.Drawing.Point(772, 102);
            this.BtnExportExcel.Name = "BtnExportExcel";
            this.BtnExportExcel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnExportExcel.OnDisabledState.BorderRadius = 1;
            this.BtnExportExcel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnExportExcel.OnDisabledState.BorderThickness = 1;
            this.BtnExportExcel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnExportExcel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnExportExcel.OnDisabledState.IconLeftImage = null;
            this.BtnExportExcel.OnDisabledState.IconRightImage = null;
            this.BtnExportExcel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnExportExcel.onHoverState.BorderRadius = 1;
            this.BtnExportExcel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnExportExcel.onHoverState.BorderThickness = 1;
            this.BtnExportExcel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnExportExcel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnExportExcel.onHoverState.IconLeftImage = null;
            this.BtnExportExcel.onHoverState.IconRightImage = null;
            this.BtnExportExcel.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.BtnExportExcel.OnIdleState.BorderRadius = 1;
            this.BtnExportExcel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnExportExcel.OnIdleState.BorderThickness = 1;
            this.BtnExportExcel.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.BtnExportExcel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnExportExcel.OnIdleState.IconLeftImage = null;
            this.BtnExportExcel.OnIdleState.IconRightImage = null;
            this.BtnExportExcel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnExportExcel.OnPressedState.BorderRadius = 1;
            this.BtnExportExcel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnExportExcel.OnPressedState.BorderThickness = 1;
            this.BtnExportExcel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnExportExcel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnExportExcel.OnPressedState.IconLeftImage = null;
            this.BtnExportExcel.OnPressedState.IconRightImage = null;
            this.BtnExportExcel.Size = new System.Drawing.Size(117, 39);
            this.BtnExportExcel.TabIndex = 9;
            this.BtnExportExcel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnExportExcel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnExportExcel.TextMarginLeft = 0;
            this.BtnExportExcel.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnExportExcel.UseDefaultRadiusAndThickness = true;
            this.BtnExportExcel.Click += new System.EventHandler(this.BtnExportExcel_Click);
            // 
            // bunifuDatePicker2
            // 
            this.bunifuDatePicker2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuDatePicker2.BorderColor = System.Drawing.Color.Silver;
            this.bunifuDatePicker2.BorderRadius = 1;
            this.bunifuDatePicker2.Color = System.Drawing.Color.Silver;
            this.bunifuDatePicker2.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.bunifuDatePicker2.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.bunifuDatePicker2.DisabledColor = System.Drawing.Color.Gray;
            this.bunifuDatePicker2.DisplayWeekNumbers = false;
            this.bunifuDatePicker2.DPHeight = 0;
            this.bunifuDatePicker2.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.bunifuDatePicker2.FillDatePicker = false;
            this.bunifuDatePicker2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuDatePicker2.ForeColor = System.Drawing.Color.Black;
            this.bunifuDatePicker2.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuDatePicker2.Icon")));
            this.bunifuDatePicker2.IconColor = System.Drawing.Color.Gray;
            this.bunifuDatePicker2.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.bunifuDatePicker2.LeftTextMargin = 5;
            this.bunifuDatePicker2.Location = new System.Drawing.Point(345, 109);
            this.bunifuDatePicker2.MinimumSize = new System.Drawing.Size(4, 32);
            this.bunifuDatePicker2.Name = "bunifuDatePicker2";
            this.bunifuDatePicker2.Size = new System.Drawing.Size(248, 32);
            this.bunifuDatePicker2.TabIndex = 8;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.Location = new System.Drawing.Point(345, 87);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(40, 15);
            this.bunifuLabel2.TabIndex = 7;
            this.bunifuLabel2.Text = "To Date";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuDatePicker1
            // 
            this.bunifuDatePicker1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuDatePicker1.BorderColor = System.Drawing.Color.Silver;
            this.bunifuDatePicker1.BorderRadius = 1;
            this.bunifuDatePicker1.Color = System.Drawing.Color.Silver;
            this.bunifuDatePicker1.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.bunifuDatePicker1.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.bunifuDatePicker1.DisabledColor = System.Drawing.Color.Gray;
            this.bunifuDatePicker1.DisplayWeekNumbers = false;
            this.bunifuDatePicker1.DPHeight = 0;
            this.bunifuDatePicker1.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.bunifuDatePicker1.FillDatePicker = false;
            this.bunifuDatePicker1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuDatePicker1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDatePicker1.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuDatePicker1.Icon")));
            this.bunifuDatePicker1.IconColor = System.Drawing.Color.Gray;
            this.bunifuDatePicker1.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.bunifuDatePicker1.LeftTextMargin = 5;
            this.bunifuDatePicker1.Location = new System.Drawing.Point(21, 109);
            this.bunifuDatePicker1.MinimumSize = new System.Drawing.Size(4, 32);
            this.bunifuDatePicker1.Name = "bunifuDatePicker1";
            this.bunifuDatePicker1.Size = new System.Drawing.Size(248, 32);
            this.bunifuDatePicker1.TabIndex = 6;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.Location = new System.Drawing.Point(21, 87);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(55, 15);
            this.bunifuLabel1.TabIndex = 5;
            this.bunifuLabel1.Text = "From Date";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // BtnThisMonth
            // 
            this.BtnThisMonth.AllowAnimations = true;
            this.BtnThisMonth.AllowMouseEffects = true;
            this.BtnThisMonth.AllowToggling = false;
            this.BtnThisMonth.AnimationSpeed = 200;
            this.BtnThisMonth.AutoGenerateColors = false;
            this.BtnThisMonth.AutoRoundBorders = false;
            this.BtnThisMonth.AutoSizeLeftIcon = true;
            this.BtnThisMonth.AutoSizeRightIcon = true;
            this.BtnThisMonth.BackColor = System.Drawing.Color.Transparent;
            this.BtnThisMonth.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnThisMonth.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnThisMonth.BackgroundImage")));
            this.BtnThisMonth.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnThisMonth.ButtonText = "This Month";
            this.BtnThisMonth.ButtonTextMarginLeft = 0;
            this.BtnThisMonth.ColorContrastOnClick = 45;
            this.BtnThisMonth.ColorContrastOnHover = 45;
            this.BtnThisMonth.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.BtnThisMonth.CustomizableEdges = borderEdges3;
            this.BtnThisMonth.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnThisMonth.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnThisMonth.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnThisMonth.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnThisMonth.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnThisMonth.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnThisMonth.ForeColor = System.Drawing.Color.White;
            this.BtnThisMonth.IconLeft = null;
            this.BtnThisMonth.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnThisMonth.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnThisMonth.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnThisMonth.IconMarginLeft = 11;
            this.BtnThisMonth.IconPadding = 10;
            this.BtnThisMonth.IconRight = null;
            this.BtnThisMonth.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnThisMonth.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnThisMonth.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnThisMonth.IconSize = 25;
            this.BtnThisMonth.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnThisMonth.IdleBorderRadius = 0;
            this.BtnThisMonth.IdleBorderThickness = 0;
            this.BtnThisMonth.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnThisMonth.IdleIconLeftImage = null;
            this.BtnThisMonth.IdleIconRightImage = null;
            this.BtnThisMonth.IndicateFocus = false;
            this.BtnThisMonth.Location = new System.Drawing.Point(466, 30);
            this.BtnThisMonth.Name = "BtnThisMonth";
            this.BtnThisMonth.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnThisMonth.OnDisabledState.BorderRadius = 1;
            this.BtnThisMonth.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnThisMonth.OnDisabledState.BorderThickness = 1;
            this.BtnThisMonth.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnThisMonth.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnThisMonth.OnDisabledState.IconLeftImage = null;
            this.BtnThisMonth.OnDisabledState.IconRightImage = null;
            this.BtnThisMonth.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnThisMonth.onHoverState.BorderRadius = 1;
            this.BtnThisMonth.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnThisMonth.onHoverState.BorderThickness = 1;
            this.BtnThisMonth.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnThisMonth.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnThisMonth.onHoverState.IconLeftImage = null;
            this.BtnThisMonth.onHoverState.IconRightImage = null;
            this.BtnThisMonth.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.BtnThisMonth.OnIdleState.BorderRadius = 1;
            this.BtnThisMonth.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnThisMonth.OnIdleState.BorderThickness = 1;
            this.BtnThisMonth.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.BtnThisMonth.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnThisMonth.OnIdleState.IconLeftImage = null;
            this.BtnThisMonth.OnIdleState.IconRightImage = null;
            this.BtnThisMonth.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnThisMonth.OnPressedState.BorderRadius = 1;
            this.BtnThisMonth.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnThisMonth.OnPressedState.BorderThickness = 1;
            this.BtnThisMonth.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnThisMonth.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnThisMonth.OnPressedState.IconLeftImage = null;
            this.BtnThisMonth.OnPressedState.IconRightImage = null;
            this.BtnThisMonth.Size = new System.Drawing.Size(93, 31);
            this.BtnThisMonth.TabIndex = 4;
            this.BtnThisMonth.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnThisMonth.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnThisMonth.TextMarginLeft = 0;
            this.BtnThisMonth.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnThisMonth.UseDefaultRadiusAndThickness = true;
            // 
            // BtnCustomDate
            // 
            this.BtnCustomDate.AllowAnimations = true;
            this.BtnCustomDate.AllowMouseEffects = true;
            this.BtnCustomDate.AllowToggling = false;
            this.BtnCustomDate.AnimationSpeed = 200;
            this.BtnCustomDate.AutoGenerateColors = false;
            this.BtnCustomDate.AutoRoundBorders = false;
            this.BtnCustomDate.AutoSizeLeftIcon = true;
            this.BtnCustomDate.AutoSizeRightIcon = true;
            this.BtnCustomDate.BackColor = System.Drawing.Color.Transparent;
            this.BtnCustomDate.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnCustomDate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCustomDate.BackgroundImage")));
            this.BtnCustomDate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCustomDate.ButtonText = "Custom";
            this.BtnCustomDate.ButtonTextMarginLeft = 0;
            this.BtnCustomDate.ColorContrastOnClick = 45;
            this.BtnCustomDate.ColorContrastOnHover = 45;
            this.BtnCustomDate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.BtnCustomDate.CustomizableEdges = borderEdges4;
            this.BtnCustomDate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCustomDate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCustomDate.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnCustomDate.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnCustomDate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCustomDate.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnCustomDate.ForeColor = System.Drawing.Color.White;
            this.BtnCustomDate.IconLeft = null;
            this.BtnCustomDate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCustomDate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCustomDate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCustomDate.IconMarginLeft = 11;
            this.BtnCustomDate.IconPadding = 10;
            this.BtnCustomDate.IconRight = null;
            this.BtnCustomDate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCustomDate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCustomDate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCustomDate.IconSize = 25;
            this.BtnCustomDate.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnCustomDate.IdleBorderRadius = 0;
            this.BtnCustomDate.IdleBorderThickness = 0;
            this.BtnCustomDate.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnCustomDate.IdleIconLeftImage = null;
            this.BtnCustomDate.IdleIconRightImage = null;
            this.BtnCustomDate.IndicateFocus = false;
            this.BtnCustomDate.Location = new System.Drawing.Point(587, 28);
            this.BtnCustomDate.Name = "BtnCustomDate";
            this.BtnCustomDate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCustomDate.OnDisabledState.BorderRadius = 1;
            this.BtnCustomDate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCustomDate.OnDisabledState.BorderThickness = 1;
            this.BtnCustomDate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCustomDate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCustomDate.OnDisabledState.IconLeftImage = null;
            this.BtnCustomDate.OnDisabledState.IconRightImage = null;
            this.BtnCustomDate.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnCustomDate.onHoverState.BorderRadius = 1;
            this.BtnCustomDate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCustomDate.onHoverState.BorderThickness = 1;
            this.BtnCustomDate.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnCustomDate.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCustomDate.onHoverState.IconLeftImage = null;
            this.BtnCustomDate.onHoverState.IconRightImage = null;
            this.BtnCustomDate.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.BtnCustomDate.OnIdleState.BorderRadius = 1;
            this.BtnCustomDate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCustomDate.OnIdleState.BorderThickness = 1;
            this.BtnCustomDate.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.BtnCustomDate.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCustomDate.OnIdleState.IconLeftImage = null;
            this.BtnCustomDate.OnIdleState.IconRightImage = null;
            this.BtnCustomDate.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnCustomDate.OnPressedState.BorderRadius = 1;
            this.BtnCustomDate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCustomDate.OnPressedState.BorderThickness = 1;
            this.BtnCustomDate.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnCustomDate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCustomDate.OnPressedState.IconLeftImage = null;
            this.BtnCustomDate.OnPressedState.IconRightImage = null;
            this.BtnCustomDate.Size = new System.Drawing.Size(93, 31);
            this.BtnCustomDate.TabIndex = 3;
            this.BtnCustomDate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCustomDate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCustomDate.TextMarginLeft = 0;
            this.BtnCustomDate.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCustomDate.UseDefaultRadiusAndThickness = true;
            // 
            // BtnLast3Days
            // 
            this.BtnLast3Days.AllowAnimations = true;
            this.BtnLast3Days.AllowMouseEffects = true;
            this.BtnLast3Days.AllowToggling = false;
            this.BtnLast3Days.AnimationSpeed = 200;
            this.BtnLast3Days.AutoGenerateColors = false;
            this.BtnLast3Days.AutoRoundBorders = false;
            this.BtnLast3Days.AutoSizeLeftIcon = true;
            this.BtnLast3Days.AutoSizeRightIcon = true;
            this.BtnLast3Days.BackColor = System.Drawing.Color.Transparent;
            this.BtnLast3Days.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnLast3Days.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnLast3Days.BackgroundImage")));
            this.BtnLast3Days.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLast3Days.ButtonText = "Last 3 Days";
            this.BtnLast3Days.ButtonTextMarginLeft = 0;
            this.BtnLast3Days.ColorContrastOnClick = 45;
            this.BtnLast3Days.ColorContrastOnHover = 45;
            this.BtnLast3Days.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.BtnLast3Days.CustomizableEdges = borderEdges5;
            this.BtnLast3Days.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnLast3Days.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnLast3Days.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnLast3Days.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnLast3Days.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnLast3Days.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnLast3Days.ForeColor = System.Drawing.Color.White;
            this.BtnLast3Days.IconLeft = null;
            this.BtnLast3Days.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnLast3Days.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnLast3Days.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnLast3Days.IconMarginLeft = 11;
            this.BtnLast3Days.IconPadding = 10;
            this.BtnLast3Days.IconRight = null;
            this.BtnLast3Days.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnLast3Days.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnLast3Days.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnLast3Days.IconSize = 25;
            this.BtnLast3Days.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnLast3Days.IdleBorderRadius = 0;
            this.BtnLast3Days.IdleBorderThickness = 0;
            this.BtnLast3Days.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnLast3Days.IdleIconLeftImage = null;
            this.BtnLast3Days.IdleIconRightImage = null;
            this.BtnLast3Days.IndicateFocus = false;
            this.BtnLast3Days.Location = new System.Drawing.Point(345, 28);
            this.BtnLast3Days.Name = "BtnLast3Days";
            this.BtnLast3Days.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnLast3Days.OnDisabledState.BorderRadius = 1;
            this.BtnLast3Days.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLast3Days.OnDisabledState.BorderThickness = 1;
            this.BtnLast3Days.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnLast3Days.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnLast3Days.OnDisabledState.IconLeftImage = null;
            this.BtnLast3Days.OnDisabledState.IconRightImage = null;
            this.BtnLast3Days.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnLast3Days.onHoverState.BorderRadius = 1;
            this.BtnLast3Days.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLast3Days.onHoverState.BorderThickness = 1;
            this.BtnLast3Days.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnLast3Days.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnLast3Days.onHoverState.IconLeftImage = null;
            this.BtnLast3Days.onHoverState.IconRightImage = null;
            this.BtnLast3Days.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.BtnLast3Days.OnIdleState.BorderRadius = 1;
            this.BtnLast3Days.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLast3Days.OnIdleState.BorderThickness = 1;
            this.BtnLast3Days.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.BtnLast3Days.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnLast3Days.OnIdleState.IconLeftImage = null;
            this.BtnLast3Days.OnIdleState.IconRightImage = null;
            this.BtnLast3Days.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnLast3Days.OnPressedState.BorderRadius = 1;
            this.BtnLast3Days.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLast3Days.OnPressedState.BorderThickness = 1;
            this.BtnLast3Days.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnLast3Days.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnLast3Days.OnPressedState.IconLeftImage = null;
            this.BtnLast3Days.OnPressedState.IconRightImage = null;
            this.BtnLast3Days.Size = new System.Drawing.Size(93, 31);
            this.BtnLast3Days.TabIndex = 2;
            this.BtnLast3Days.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnLast3Days.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnLast3Days.TextMarginLeft = 0;
            this.BtnLast3Days.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnLast3Days.UseDefaultRadiusAndThickness = true;
            // 
            // BtnThisWeek
            // 
            this.BtnThisWeek.AllowAnimations = true;
            this.BtnThisWeek.AllowMouseEffects = true;
            this.BtnThisWeek.AllowToggling = false;
            this.BtnThisWeek.AnimationSpeed = 200;
            this.BtnThisWeek.AutoGenerateColors = false;
            this.BtnThisWeek.AutoRoundBorders = false;
            this.BtnThisWeek.AutoSizeLeftIcon = true;
            this.BtnThisWeek.AutoSizeRightIcon = true;
            this.BtnThisWeek.BackColor = System.Drawing.Color.Transparent;
            this.BtnThisWeek.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnThisWeek.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnThisWeek.BackgroundImage")));
            this.BtnThisWeek.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnThisWeek.ButtonText = "This Week";
            this.BtnThisWeek.ButtonTextMarginLeft = 0;
            this.BtnThisWeek.ColorContrastOnClick = 45;
            this.BtnThisWeek.ColorContrastOnHover = 45;
            this.BtnThisWeek.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.BtnThisWeek.CustomizableEdges = borderEdges6;
            this.BtnThisWeek.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnThisWeek.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnThisWeek.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnThisWeek.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnThisWeek.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnThisWeek.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnThisWeek.ForeColor = System.Drawing.Color.White;
            this.BtnThisWeek.IconLeft = null;
            this.BtnThisWeek.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnThisWeek.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnThisWeek.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnThisWeek.IconMarginLeft = 11;
            this.BtnThisWeek.IconPadding = 10;
            this.BtnThisWeek.IconRight = null;
            this.BtnThisWeek.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnThisWeek.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnThisWeek.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnThisWeek.IconSize = 25;
            this.BtnThisWeek.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnThisWeek.IdleBorderRadius = 0;
            this.BtnThisWeek.IdleBorderThickness = 0;
            this.BtnThisWeek.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnThisWeek.IdleIconLeftImage = null;
            this.BtnThisWeek.IdleIconRightImage = null;
            this.BtnThisWeek.IndicateFocus = false;
            this.BtnThisWeek.Location = new System.Drawing.Point(224, 28);
            this.BtnThisWeek.Name = "BtnThisWeek";
            this.BtnThisWeek.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnThisWeek.OnDisabledState.BorderRadius = 1;
            this.BtnThisWeek.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnThisWeek.OnDisabledState.BorderThickness = 1;
            this.BtnThisWeek.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnThisWeek.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnThisWeek.OnDisabledState.IconLeftImage = null;
            this.BtnThisWeek.OnDisabledState.IconRightImage = null;
            this.BtnThisWeek.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnThisWeek.onHoverState.BorderRadius = 1;
            this.BtnThisWeek.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnThisWeek.onHoverState.BorderThickness = 1;
            this.BtnThisWeek.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnThisWeek.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnThisWeek.onHoverState.IconLeftImage = null;
            this.BtnThisWeek.onHoverState.IconRightImage = null;
            this.BtnThisWeek.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.BtnThisWeek.OnIdleState.BorderRadius = 1;
            this.BtnThisWeek.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnThisWeek.OnIdleState.BorderThickness = 1;
            this.BtnThisWeek.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.BtnThisWeek.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnThisWeek.OnIdleState.IconLeftImage = null;
            this.BtnThisWeek.OnIdleState.IconRightImage = null;
            this.BtnThisWeek.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnThisWeek.OnPressedState.BorderRadius = 1;
            this.BtnThisWeek.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnThisWeek.OnPressedState.BorderThickness = 1;
            this.BtnThisWeek.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnThisWeek.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnThisWeek.OnPressedState.IconLeftImage = null;
            this.BtnThisWeek.OnPressedState.IconRightImage = null;
            this.BtnThisWeek.Size = new System.Drawing.Size(93, 31);
            this.BtnThisWeek.TabIndex = 1;
            this.BtnThisWeek.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnThisWeek.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnThisWeek.TextMarginLeft = 0;
            this.BtnThisWeek.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnThisWeek.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.bunifuPanel2.Location = new System.Drawing.Point(0, 466);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(908, 30);
            this.bunifuPanel2.TabIndex = 2;
            // 
            // panelTransactions
            // 
            this.panelTransactions.BackgroundColor = System.Drawing.Color.Transparent;
            this.panelTransactions.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panelTransactions.BackgroundImage")));
            this.panelTransactions.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panelTransactions.BorderColor = System.Drawing.Color.Transparent;
            this.panelTransactions.BorderRadius = 3;
            this.panelTransactions.BorderThickness = 1;
            this.panelTransactions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelTransactions.Location = new System.Drawing.Point(0, 165);
            this.panelTransactions.Name = "panelTransactions";
            this.panelTransactions.ShowBorders = false;
            this.panelTransactions.Size = new System.Drawing.Size(908, 301);
            this.panelTransactions.TabIndex = 3;
            // 
            // DropDownSortByDate
            // 
            this.DropDownSortByDate.BackColor = System.Drawing.Color.Transparent;
            this.DropDownSortByDate.BackgroundColor = System.Drawing.Color.White;
            this.DropDownSortByDate.BorderColor = System.Drawing.Color.Silver;
            this.DropDownSortByDate.BorderRadius = 1;
            this.DropDownSortByDate.Color = System.Drawing.Color.Silver;
            this.DropDownSortByDate.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.DropDownSortByDate.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.DropDownSortByDate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DropDownSortByDate.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.DropDownSortByDate.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.DropDownSortByDate.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.DropDownSortByDate.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.DropDownSortByDate.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.DropDownSortByDate.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.DropDownSortByDate.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.DropDownSortByDate.FillDropDown = true;
            this.DropDownSortByDate.FillIndicator = false;
            this.DropDownSortByDate.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.DropDownSortByDate.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.DropDownSortByDate.ForeColor = System.Drawing.Color.Black;
            this.DropDownSortByDate.FormattingEnabled = true;
            this.DropDownSortByDate.Icon = null;
            this.DropDownSortByDate.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.DropDownSortByDate.IndicatorColor = System.Drawing.Color.DarkGray;
            this.DropDownSortByDate.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.DropDownSortByDate.IndicatorThickness = 2;
            this.DropDownSortByDate.IsDropdownOpened = false;
            this.DropDownSortByDate.ItemBackColor = System.Drawing.Color.White;
            this.DropDownSortByDate.ItemBorderColor = System.Drawing.Color.White;
            this.DropDownSortByDate.ItemForeColor = System.Drawing.Color.Black;
            this.DropDownSortByDate.ItemHeight = 26;
            this.DropDownSortByDate.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.DropDownSortByDate.ItemHighLightForeColor = System.Drawing.Color.White;
            this.DropDownSortByDate.ItemTopMargin = 3;
            this.DropDownSortByDate.Location = new System.Drawing.Point(21, 27);
            this.DropDownSortByDate.Name = "DropDownSortByDate";
            this.DropDownSortByDate.Size = new System.Drawing.Size(166, 32);
            this.DropDownSortByDate.TabIndex = 0;
            this.DropDownSortByDate.Text = "Sort By Date";
            this.DropDownSortByDate.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.DropDownSortByDate.TextLeftMargin = 5;
            // 
            // FrmTransactions
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(908, 496);
            this.Controls.Add(this.panelTransactions);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.bunifuShadowPanel1);
            this.Name = "FrmTransactions";
            this.Text = "Transactions";
            this.Load += new System.EventHandler(this.FrmTransactions_Load);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnThisMonth;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCustomDate;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnLast3Days;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnThisWeek;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnExportPdf;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnExportExcel;
        private Bunifu.UI.WinForms.BunifuDatePicker bunifuDatePicker2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuDatePicker bunifuDatePicker1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuPanel panelTransactions;
        private Bunifu.UI.WinForms.BunifuDropdown DropDownSortByDate;
    }
}